initial_assessment:
  description: >
    Sua tarefa é analisar o(s) documento(s) base:{document_list}, que estão divididos em chunks,
    e extrair deles, de forma detalhada, todas as informações essenciais de maneira estruturada.
    Para obter a informação do total de chunks que o documento tem, utilize a ferramenta
    FetchMetadataTool. Identifique e armazene quantos chunks cada documento possui. 
    Para obter o conteúdo dos documentos, utilize a ferramenta FetchArticlesTool. Lembre-se
    de especificar o indice da chunk que você quer acessar.

    **Elementos a serem extraídos**:
       - Tema central, objetivos e hipóteses;
       - Estrutura do texto; 
       - Métodos, resultados quantitativos e qualitativos, hipóteses, conclusões preliminares
       - Capturar insights, interpretações e pontos críticos da discussão inicial.
       - Resultados, conclusões e recomendações.

  expected_output: >
    Um relatório detalhado e estruturado, contendo todas as informações essenciais dos rascunhos 
    analisados, organizadas de maneira lógica e coesa.
  agent: analyst

query_generation:
  description: >
    Utilize as informações extraídas para formular queries que não só busquem resultados similares,
    mas também ampliem e complementem a discussão existente.
    Identifique lacunas ou pontos que podem ser aprofundados na discussão (por exemplo, inconsistências, 
    tendências inesperadas ou temas controversos). Gerar variações de queries, explorando diferentes ângulos,
    tais como “análise comparativa de [resultado específico]” ou “discussões sobre [aspecto] na literatura”.
  expected_output: >
    Uma representação estruturada no formato JSON contendo mapeando a query gerada para qual lacuna ou 
    ponto ela ataca e/ou aprofunda, dessa maneira: {<ponto/lacuna a ser aprofundada>: <query gerada>}    
  agent: analyst

query_execution:
  description: >
    Sua tarefa é receber as queries geradas pelo agente analista e executar buscas na biblioteca de artigos.
    Para cada query, utilize a ferramenta QueryArticlesTool para localizar artigos relevantes e recuperar os
    trechos essenciais que respondam à demanda. Em seguida, sintetize essas informações para gerar respostas
    integradas, realizando uma abordagem de Retrieval-Augmented Generation (RAG) que aprofunde a discussão.
    Caso ache necessário, você pode gerar novas queries, se ainda houver necessidade de maior contexto.
  expected_output: >
    Um relatório estruturado em formato JSON contendo, para cada ponto/lacuna a ser aprofundada, uma referência
    com os metadados dos trechos utilizados e sua resposta sintetizada que integra os achados com o contexto da
    discussão. A estrutura deve seguir esse formato: 
    "{<ponto/lacuna a ser aprofundada>: {"referências": [<metadados1>,...<metadadosN>], "resposta": "resposta sintetizada"}}"
  agent: researcher