merge_subsection:
  description: >
    **Topics Text JSON**:

    {topics_text_json}

    **Subsection outline**:

    {subsection_outline}

    You are provided with individual texts for each topic of the {subsection_title} subsection, along with the subsection's outline that defines the 
    intended order and content of these topics. Your task is to assemble these topic's texts into a single, continuous, and fluid subsection text, 
    refining each topic's text as needed and creating natural transitions between them, while ensuring all content specified in the outline is 
    preserved.

    **Inputs**:
    - **Topics Text JSON**: A JSON object containing the raw text content for each topic of the subsection, structured as follows:
      - `topics`: A list of topic entries, each representing a segment of the subsection's content to be refined and integrated into the final text.
        - `topic`: The title of the topic (e.g., "Comparison with Previous Studies"), which corresponds to a topic in the **Subsection Outline**'s 
          `discussion_topics`, defining its role in the subsection.
        - `text`: The raw text content for the topic, containing the technical details, visual references (e.g., "Tabela 2", "Figura 3"), and 
          contextual information to be preserved and refined for clarity and coherence.
    - **Subsection Outline**: A JSON object containing the subsection's full structure, with all topics to be presented, their visual elements and 
      numerical results that have to be included in the topic's text. This JSON is structured as follow:
      - `subsection_name`: The subsection title (e.g., "Results", "Discussion").
      - `subsection_flow`: A string of topic titles in order (e.g., "Topic1 -> Topic2").
      - `discussion_topics`: A list of topics, each with:
        - `topic`: The title of the topic, matching a topic in the `topic_texts_json`.
        - `rhetorical_purpose`: The intended purpose of the topic (e.g., "To contextualize results").
        - `topic_description`: A description of the topic's content and focus.
        - `visual_elements`: A list of tables, figures, or other visuals associated with the topic (e.g., "Tabela 2: Performance under turbulence").
        - `numerical_results`: A list of quantitative results to be included (e.g., "95% accuracy").
        - `narrative_guidance`: Instructions for the narrative style or emphasis (e.g., "Highlight superior precision").

    **Main Objectives:**
      - Assemble the final subsection text by integrating the individual topic texts in the order specified by the outline's `subsection_flow`.
      - Refine each topic's text for clarity, conciseness, and coherence, preserving all original technical details, including numerical results, visual references, and contextual connections, as specified in the topic texts and outline.
      - Create smooth, logical transitions between topics to ensure the text reads as a unified narrative.
      - Eliminate unnecessary repetitions while retaining intentional references to visual elements (e.g., re-referencing a table for comparison).
      - Maintain a formal, academic tone in Brazilian Portuguese.

    **Execution Steps:**
    1. Review the subsection outline to:
      - Understand the intended order of topics (`subsection_flow`).
      - Identify the key content for each topic, including numerical results, visual elements, and narrative guidance (`discussion_topics`).
    2. For each topic in the outline's `subsection_flow`:
      - Locate the corresponding entry in the `topic_texts_json` using the topic title.
      - Refine the topic's `text` to ensure clarity, conciseness, and alignment with its `rhetorical_purpose` and `narrative_guidance` from the outline, following the subsection-specific directives.
      - Preserve all specific details, such as study titles, numerical results, and references to visual elements (e.g., "Tabela 2", "Figura 3"), as listed in the outline’s `visual_elements` and `numerical_results` fields.
    3. Assemble the refined topic texts in the order specified by `subsection_flow`, adding minimal connectors or transitional phrases to:
      - Ensure a smooth flow from one topic to the next.
      - Maintain logical progression and thematic continuity.
    4. Manage repetitions:
      - Eliminate unnecessary reiterations of information that do not add new insight, as identified across topic texts.
      - Retain intentional references to visual elements (e.g., re-referencing a figure for analysis or comparison) and ensure they are clear and contextually appropriate, per the outline’s `visual_elements` field.
    5. Review the final assembled text to ensure:
      - All topics from the outline and topic texts are fully represented, with no omissions.
      - The text is free of unnecessary repetitions and flows naturally.
      - All numerical results, visual references, and contextual connections are preserved, as specified in both inputs.
      - The tone is formal, precise, and suitable for academic publication.
      - The text is in Brazilian Portuguese.

    **Constraints:**
      - Preserve all original technical information from both the topic texts and the outline without alteration or omission.
      - Do not introduce new information, interpretations, or remove critical content.
      - Maintain a scientific tone and academic formality.
      - Ensure the final text is in Brazilian Portuguese.

    **Success Criteria:**
      - The final text functions as a continuous, unified subsection with natural transitions between topics.
      - All original technical content from the outline and topic texts, including comparisons, limitations, contributions, future directions, numerical results, and visual references, is preserved.
      - Unnecessary repetitions are eliminated, while intentional references to visual elements are retained and clear.
      - Contextual connections are maintained, and the language is formal, precise, and suitable for academic publication.

  expected_output: >
    Um JSON com a seguinte estrutura:
    {
      "subsection_title": "{subsection_title}",
      "merged_text": "Texto reestruturado, fluido e contínuo da subseção, escrito em português brasileiro acadêmico."
    }
  agent: subsection_merger
