topic_research:
  description: >
    topico de discussao:
    {discussion_topic}

    Você deve pesquisar sobre o *topico de discussao* informado acima, a ser discutido na subseção "{section_title}" da seção "Resultados e Discussão" de um 
    artigo científico. Utilize a ferramenta QueryArticlesTool para realizar a pesquisa.

    **Passos de obrigatórios da tarefa:**
    1. Pesquise sobre o topico de discussao "{discussion_topic}" utilizando a ferramenta `QueryArticlesTool`. Para isso:
      - Use o tópico como valor do parametro 'search_query'
      - Defina o parâmetro 'doc_type' como ['reference', 'draft', 'report'];
      - Defina o parâmetro 'top_k' como 5;
      - Execute a ferramenta `QueryArticlesTool` e registre o resultado;
      - Se não forem retornardos bons trechos pela ferramenta, aumente o valor de 'top_k' e repita a execução da ferramenta.

    **Restrições:**
      - Não defina 'top_k' com um valor menor que 5.

    **Criterio de sucesso:**
      - A ferramenta foi executada corretamente e retornou trechos de maior alinhamento com o tópico
  expected_output: >
    Um JSON contendo a chave "about_the_topic", cujo valor é um objeto possuindo os pares chave-valor:
      - "item_name": Nome do tópico pesquisado;
      - "research_results": o conteúdo retornado pela ferramenta QueryArticlesTool.
  agent: topic_researcher

visual_elements_research:
  description: >
    Lista de Elementos visuais:

    {visual_elements_to_contextualize}

    Você deve pesquisar sobre cada item listado acima, caso existam, para serem discutidos e incluídos na subseção "{section_title}" da seção "Resultados e Discussão" 
    de um artigo científico. Utilize a ferramenta `QueryArticlesTool` para realizar cada uma das pesquisas.

    **Passos obrigatórios da tarefa:**
    1. Elabore um plano de execução. Este plano deve listar cada item da lista de elementos visuais, indicar que será feita uma pesquisa separada para cada um,
       e especificar que o tipo de documento a ser consultado será sempre 'report' e 'draft'.
    2. Execute o plano de forma sequencial. Para cada item:
       - Use o item como valor do parâmetro 'search_query';
       - Defina o parâmetro 'doc_type' como ['report', 'draft'];
       - Defina o parâmetro 'top_k' como 5;
       - Execute a ferramenta `QueryArticlesTool` e registre o resultado;
       - Se não forem retornardos bons trechos pela ferramenta, aumente o valor de 'top_k' e repita a execução da ferramenta.

    **Restrições:**
      - Execute apenas se a lista de elementos visuais não estiver vazia.
      - Pesquise exclusivamente em documentos do tipo 'report' e 'draft'.

    **Critério de sucesso:**
      - A ferramenta foi chamada uma vez para cada item da lista (se existirem), e retornou os trechos mais alinhados com o conteúdo do item visual pesquisado.
  expected_output: >
    Um JSON contendo a chave "about_the_visual_elements". O valor deve ser:
      - Uma lista de objetos (um por item visual pesquisado), onde cada objeto possui:
          - "item_name": o nome do item pesquisado;
          - "research_results": o conteúdo retornado pela QueryArticlesTool.
      - Ou uma lista vazia, caso nenhum item tenha sido fornecido para pesquisa.
  agent: topic_researcher

numerical_results_research:
  description: >
    Lista de Resultados numericos:
    
    {numerical_results_to_include}

    Você deve pesquisar sobre cada item listado acima, caso existam, para serem discutidos e incluídos na subseção "{section_title}" da seção "Resultados e Discussão" 
    de um artigo científico. Utilize a ferramenta `QueryArticlesTool` para realizar cada uma das pesquisas.

    **Passos obrigatórios da tarefa:**
    1. Elabore um plano de execução. Este plano deve listar cada item da lista de Resultados numericos, indicar que será feita uma pesquisa separada para cada um,
       e especificar que o tipo de documento a ser consultado será sempre 'draft'.
    2. Execute o plano de forma sequencial. Para cada item:
       - Use o item como valor do parâmetro 'search_query';
       - Defina o parâmetro 'doc_type' como ['draft'];
       - Defina o parametro 'top_k' como 5;
       - Execute a ferramenta `QueryArticlesTool` e registre o resultado;
       - Se não forem retornardos bons trechos pela ferramenta, aumente o valor de 'top_k' e repita a execução da ferramenta.

    **Restrições:**
      - Execute apenas se a lista de elementos visuais não estiver vazia.
      - Pesquise exclusivamente em documentos do tipo 'draft'.

    **Critério de sucesso:**
      - A ferramenta foi chamada uma vez para cada item da lista (se existirem), e retornou os trechos mais alinhados com o conteúdo do item visual pesquisado.
  expected_output: >
    Um JSON contendo a chave "about_the_numerical_results". O valor deve ser:
      - Uma lista de objetos (um por item visual pesquisado), onde cada objeto possui:
          - "item_name": o nome do item pesquisado;
          - "research_results": o conteúdo retornado pela QueryArticlesTool.
      - Ou uma lista vazia, caso nenhum item tenha sido fornecido para pesquisa.
  agent: topic_researcher

gather_insights:
  description: >
    Agora que todas as pesquisas foram realizadas, escreva insights detalhados com base nos resultados das tasks anteriores:

    - `topic_research`: pesquisa sobre o tópico principal;
    - `visual_elements_research`: pesquisa sobre os elementos visuais;
    - `numerical_results_research`: pesquisa sobre os resultados numéricos.

    Seu texto deve ser sobre o tópico:
    "{discussion_topic}"

    Use os dados fornecidos no contexto. Não execute novas pesquisas. Escreva um texto técnico, em português brasileiro, com linguagem formal, entre 400 e 600 palavras, integrando:

    - O conteúdo da pesquisa sobre o tópico central;
    - As informações obtidas sobre os elementos visuais;
    - E os resultados numéricos relevantes, com valores mantidos com exatidão.

    **Passos para a tarefa:**
    1. Leia atentamente os resultados das tasks anteriores (`topic_research`, `visual_elements_research`, `numerical_results_research`) que estarão disponíveis para você no 
       contexto desta tarefa;
    2. Redija um texto técnico com insights sobre o tópico "{discussion_topic}", incluindo argumentações, dados e ligações entre os elementos, se baseando nos resultados 
       lidos anteriormente.
    
    **Restrições:**
      - Não altere ou crie chaves adicionais no resultado.
      - A chave tópico sempre dever ser "{discussion_topic}"
      - O texto deve fornecer insights unica e exclusivamente sobre o tópico {discussion_topic}
      - Sua resposta com os insights sobre tópico não deve ter menos que 200 palavras;
      - Sua resposta com os insights sobre tópico não deve ter mais que 600 palavras;
      - Você deve preservar resultados numéricos de alta relevancia em sua resposta;
      - Sua resposta deve ser escrita em português brasileiro.

    **Criterios para sucesso**:
      - Os insights gerados são sobre o tópico: {discussion_topic};
      - O texto gerado para os apresentar os insights está escrito em português brasileiro;
      - Os insights gerados são baseados nos resultados das pesquisas e de extrema relevancia ao tópico {discussion_topic};
      - Os insights gerados são extremamente detalhados e conseguem ser utilizados para criar textos sobre o topico {discussion_topic}.
  expected_output: >
    Um objeto JSON contendo as seguintes duas chaves com os seguintes valores:
      - "topic": O nome do tópico ao qual os insights são sobre, nesse caso {discussion_topic}
      - "insights": Insights detalhados sobre o tópico "{discussion_topic}", escritos em texto de 400 a 600 palavras, em português brasileiro.
  agent: insight_writer
  context: [topic_research, visual_elements_research, numerical_results_research]
