research_outline_topics:
  description: >
    A partir do outline do capítulo de **Resultados e Discussão** para um artigo científico, utilize a ferramenta 
    `QueryArticlesTool` para realizar consultas à base de dados vetorizada e crie respostas que tragam informações 
    e argumentação extras para os tópicos do outline, com o objetivo de enriquecer o texto do capítulo.
    
    Você deve identificar conteúdos técnicos, metodológicos ou analíticos que possam ser usados para apoiar ou 
    aprofundar um ou mais tópicos do outline, tendo a certeza de atacar a todos.

    Para cada seção ou subseção do outline:
      - Gere uma ou mais queries baseadas no título e na descrição;
      - Execute as buscas com a ferramenta `QueryArticlesTool`;
      - Analise os resultados retornados e produza um **bloco de apoio técnico** por seção, contendo:
        - Um resumo sintético dos achados mais relevantes;
        - Tópicos ou artigos sugeridos para citação (com IDs, autores ou títulos se disponíveis);
        - Sugestões específicas sobre como o escritor pode aproveitar o material encontrado (ex: comparar resultados, reforçar argumentação, inserir gráficos).

    Nunca repita o conteúdo do outline nem gere conteúdo fictício. Baseie-se exclusivamente nos retornos da ferramenta.

    Outline:

    {chapter_outline}

select_complementary_elements:
  description: >
    Utilize o outline fornecido do capítulo **Resultados e Discussão**, para obter da lista de elementos complementares,
    tabelas, trechos de código, equações matemáticas, gráficos e/ou figuras, que você julgue complementar a argumentação
    do capítulo, inferindo a partir do esqueleto proposto pelo outline.

    O objetivo é que você selecione os elementos melhor irão se encaixar e enriquecer o conteúdo a ser escrito por você,
    posteriormente, do capítulo de **Resultados e Discussão** do artigo cietífico.

    Para tanto, você deve LER O OUTLINE do capítulo de **Resultados e Discussão** e, em seguida, selecionar os elementos
    complementares que você julgar mais relevantes para o capítulo, copiandos na integra da lista de elementos complementares
    e incluindo anotações de onde você irá utilizá-los, dessa forma facilitando seu trabalho durante a escrita.

    Outline do capítulo de **Resultados e Discussão**:

    {chapter_outline}

    Lista de elementos complementares:

    {technical_report}

  expected_output: >
    Uma lista no exato mesmo formato da Lista de elementos complementares, incluindo ao final de cada item da lista
    uma nota de uso, de modo a facilitar a inclusão dos elementos complementares no capítulo de **Resultados e Discussão**,
    eliminando a necessidade de uma nova inferência. Cada elemento dessa nova lista a ser composta, deverá seguir a seguinte
    estrutura:

    * tipo: <tipo do elemento: tabela | código | equação | figura>
      * descrição: <descrição curta do uso do elemento no texto>
      * conteúdo: <conteúdo literal extraído, mantendo formatação original>
      * nota de uso: <nota de uso para facilitar a inclusão do elemento no texto>

    Exemplo:
    * tipo: tabela
      * descrição: Tabela com relação entre variáveis X e Y.
      * conteúdo:
        \BEGIN{TABLE}[H!]
          \CENTERING
          \CAPTION{TABELA 1: Correlação entre X e Y}
          ...
      * nota de uso: Inserir após a discussão sobre a relação entre X e Y (ponto 3 do outline).
  agent: results_discussion_writer

results_discussion_writting:
  description: >
    Escreva o capítulo completo de **Resultados e Discussão** para um artigo científico com base na estrutura detalhada 
    do capítulo, FORNECIDA PELO OUTLINE, incluindo os elementos complementares selecionados e anotados anteriormente,
    pela tarefa `select_complementary_elements`.

    Para garantir uma excelente argumentação, pesquise os itens do outline na literatura disponível, através da sua 
    ferramenta QueryArticlesTool, e utilize os trechos retornados por ela para compor a sua escrita, evitando plágio.
    Caso necessário cópia direta de algum dos trechos, referêncie-os adequadamente.

    Tenha a certeza de seguir rigorosamente a estrutura proposta no outline e as melhores práticas de redação ciêntífica,
    além de utilizar os elementos complementares da lista resultante da tarefa `select_complementary_elements` para 
    fortalecer a argumentação do capítulo, incluindo os itens nela dispostos (tabelas, códigos, figuras, equações) levando
    em conta a NOTA DE USO de cada um.

    O capítulo deve atender aos seguintes critérios:
    - Clareza e concisão na apresentação dos resultados;
    - Discussão crítica dos achados, relacionando-os aos objetivos do estudo e à literatura científica existente;
    - Integração de elementos técnicos relevantes, respeitando a sequência lógica do texto;
    - Estilo acadêmico formal, adequado à publicação científica;
    - Formatação em LaTeX, com organização típica de artigos (seções, subseções, equações numeradas, figuras e tabelas 
      referenciadas no texto).

    O objetivo final é ter um capítulo completo de **Resultados e Discussão** para um artigo ciêntífico, que requeira o mínimo
    de edição a posteriori, e que seja capaz de ser publicado em uma revista científica de alto rigor.

    Outline:
    
    {chapter_outline}

  expected_output: >  
    Um capítulo finalizado de **Resultados e Discussão**, formatação em LaTeX, com organização típica de artigos (seções, 
    subseções, equações numeradas, figuras e tabelas referenciadas no texto), BASEADO NO OUTLINE FORNECIDO, com conteúdo 
    enriquecido com os elementos complementares fornecidos pela lista resultante da tarefa `select_complementary_elements`.

    O texto deve ser entregue em LaTeX completo, com:
    - Introdução aos resultados;
    - Subseção de apresentação e descrição analítica e crítica dos resultados;
    - Subseção de discussão, com interpretações, comparações com a literatura e implicações do estudo;
    - Inclusão de elementos complementares que enriqueçam o texto;
    - Referências integradas diretamente na narrativa, conforme os padrões de citação.
   
  agent: results_discussion_writer
  context: [select_complementary_elements]
  output_file: output/results_discussion.tex