research_outline_topics:
  description: >
    A partir do outline da seção **Resultados e Discussão** de um artigo científico, utilize a ferramenta `QueryArticlesTool` 
    para realizar consultas à base de dados vetorizada, identificando conteúdos técnicos, metodológicos ou analíticos que 
    possam ser usados para apoiar ou aprofundar cada tópico do outline.

    Para cada seção ou subseção do outline:
      - Gere uma ou mais queries baseadas no título e na descrição;
      - Execute as buscas com a ferramenta `QueryArticlesTool`;
      - Analise os resultados retornados e produza um **bloco de apoio técnico** por seção, contendo:
        - Um resumo sintético dos achados mais relevantes;
        - Tópicos ou artigos sugeridos para citação (com IDs, autores ou títulos se disponíveis);
        - Sugestões específicas sobre como o escritor pode aproveitar o material encontrado (ex: comparar resultados, reforçar argumentação, inserir gráficos).

    Nunca repita o conteúdo do outline nem gere conteúdo fictício. Baseie-se exclusivamente nos retornos da ferramenta.

    Outline:

    {chapter_outline}

  expected_output: >
    Um relatório técnico organizado por seção do outline, contendo para cada uma:
    - O título e descrição da seção original;
    - A(s) query(s) utilizadas;
    - Um resumo dos achados relevantes oriundos da base vetorizada;
    - Artigos ou fontes sugeridas (com [ref:ID], título ou autores se disponíveis);
    - Sugestões claras de como usar esse material no texto final.
  agent: research_agent

results_discussion_writting:
  description: >
    Escreva o capítulo completo de **Resultados e Discussão** para um artigo científico com base na estrutura detalhada 
    do capítulo, fornecida pelo OUTLINE, se embasando no Relatório técnico com referências e sugestões de aprofundamento, 
    gerado pelo seu colega pesquisador.

    Tenha a certeza de seguir rigorosamente a estrutura proposta no outline e utilizar as informações do relatório técnico 
    provido pelo Pesquisador técnico para tópicos científicos, para embasar e 
    fortalecer a argumentação científica, incorporando as referências de maneira fluida ao longo do texto. Além disso, 
    incluir ELEMENTOS TÉCNICOS (tabelas, códigos, figuras, equações) referenciados no outline, disponíveis no relatório
    técnico, integralmente, de forma natural no corpo do texto, respeitando a fluidez e a clareza da exposição.

    O capítulo deve atender aos seguintes critérios:
    - Clareza e concisão na apresentação dos resultados;
    - Discussão crítica dos achados, relacionando-os aos objetivos do estudo e à literatura científica existente;
    - Integração de elementos técnicos (quando mencionados), respeitando a sequência lógica do texto;
    - Inclusão direta das referências obtidas no relatório técnico, com formatação adequada (ex: "como demonstrado em [Autor, Ano]");
    - Estilo acadêmico formal, adequado à publicação científica;
    - Formatação em LaTeX, com organização típica de artigos (seções, subseções, equações numeradas, figuras e tabelas 
      referenciadas no texto).

    Outline:
    
    {chapter_outline}

    Relatório técnico:

    {technical_report}

  expected_output: >  
    Um capítulo finalizado de **Resultados e Discussão** para o tema "{theme}", com estrutura baseada no OUTLINE
    fornecido e conteúdo enriquecido com base nas sugestões e referências fornecidas pelo Pesquisador técnico para 
    tópicos científicos.

    O texto deve ser entregue em LaTeX completo, com:
    - Introdução aos resultados;
    - Subseção de apresentação e descrição analítica dos resultados;
    - Subseção de discussão, com interpretações, comparações com a literatura e implicações do estudo;
    - Inclusão de elementos técnicos no ponto adequado do texto;
    - Referências integradas diretamente na narrativa, conforme os padrões de citação.
   
  agent: results_discussion_writer
  context: [research_outline_topics]
  output_file: output/results_discussion.tex