redacao_conclusao:
  description: >
    Elaborar a conclusão de um artigo científico com base na seção de Resultados 
    e Discussão fornecida, garantindo uma síntese clara, objetiva e rigorosa.

    - **Síntese dos principais resultados**: Resumir de forma concisa os principais 
      achados do estudo, destacando sua relevância.  
    - **Conexão com os objetivos do estudo**: Demonstrar se os objetivos iniciais 
      foram atingidos, sem repetir informações detalhadas.  
    - **Implicações e relevância**: Explicar a importância dos achados no contexto 
      da área de pesquisa.  
    - **Limitações do estudo**: Abordar limitações metodológicas de forma honesta 
      e equilibrada.  
    - **Sugestões para pesquisas futuras**: Propor novas direções de pesquisa 
      baseadas nos achados e limitações.  
    - **Evitar informações novas**: Garantir que nenhum novo dado ou discussão 
      seja introduzido na conclusão.  
    - **Clareza e objetividade**: Utilizar linguagem acadêmica clara, sem exageros 
      ou afirmações subjetivas.  
    - **Concordância com a discussão**: Certificar-se de que as conclusões derivam 
      diretamente da seção de Discussão, sem extrapolações injustificadas.  
    - **Encerramento impactante**: Finalizar com uma frase que reforce a relevância 
      do estudo e suas contribuições para a área.  

    Seção Resultados e Discussão do tema {article_theme}:
    {results_and_discution_section}

  expected_output: >
    Um texto de conclusão acadêmica bem estruturado, apresentando:
    - Síntese clara dos principais achados.  
    - Relação dos resultados com os objetivos da pesquisa.  
    - Discussão das implicações e limitações do estudo.  
    - Sugestões para futuras pesquisas.  
    - Um fechamento forte e impactante.  

  agent: redator_conclusao