research_and_write_sections:
  description: >
    CHAPTER OUTLINE:

    {chapter_outline}

    Analyze the chapter outline for the chapter "{chapter_title}", and gather information and insights about every *topic to include* and *numerical 
    results*, for every level of the chapter's structure, in other to get a solid foundation for when it's time to write the content.
    For each topic to include in the section or subsection content, create a specific research subtask, with the objective of obtaining insights to 
    anchor the text content. The insights gathered should be included at the end of the outline of the section.

    **Execution Process:**
      1. Analyze the ouline line by line.
      2. When a *topics to include* list is identifed, note from which section or subsection it belongs. After this, begin this iterative process:
        - For each topic in the topics to include list of the section or subsection, research for insights and obtain the necessary arguments for writing;
        - This research must be conducted by a specialized researcher member of your team.
      3. When a *visual elements to include* list is identifed, do the same steps for the *topics to include* list.
      4. When a *results to include* list is identifed, do the same steps for the *topics to include* list, but make sure to instruct the researcher to 
      conduct its job only on documents of type 'draft'

      5. After a research has been concluded, include after the topic that was researched an item named *Insights*, that includes the insights founded in the
      chapter_outline.

    **Restrictions:**
      - No section or subsection not listed in the outline may be created;

    **Success Criteria:** 
      - All topics were researched by specialized agents;
      - Insights were included in the outline;
  expected_output: |
    A slightly modified version of the provided chapter outline, including the insights gathered.

    example:
    ### Resultados
    Tópicos a abordar no texto:
    - DESCREVER a eficiência do algoritmo genético na convergência das soluções ao longo das gerações.
    - Insights: O algoritmo genético obteve excelencia em 50 gerações.
      Elementos visuais a incluir:
      - **Elemento visual:** Figura 13 - Evolução do fitness para a primeira porta.
      - **Elemento visual:** Figura 15 - Evolução do fitness para a segunda porta.
      Resultados a incluir:
      - **Resultado numérico:** Saturação observada por volta da 30ª e 50ª gerações.
    - ANALISAR os resultados das tabelas verdade para validar a funcionalidade lógica da porta OR com cinco entradas.
    - Insights: no caso 0 0 0 0 0 CR(OUT) = 0,012 db
      Elementos visuais a incluir:
      - **Elemento visual:** Tabela 1 - Contrastes da primeira porta.
      - **Elemento visual:** Tabela 2 - Contrastes da segunda porta.
      Resultados a incluir:
      - **Resultado numérico:** CR(Out) > 0,30 em 100% dos casos simulados.
  agent: topic_researcher

assemble_and_finalize_chapter:
  description: >
    CHAPTER OUTLINE:

    {chapter_outline}

    Assemble the chapter "{chapter_title}" using the structured section texts provided. Organize the content hierarchically in LaTeX, 
    ensuring strict adherence to the structure and topics defined in the outline. If any issues are flagged during the editing phase, 
    delegate new tasks to fix them and proceed with a maximum of 5 revision cycles.

    **Execution Process:**
      1. Analyze the chapter outline to extract the chapter's structure. Note where each prewritten section/subsection text should be allocated.

      2. Assemble them according to the chapter's structure to form the complete chapter. Instruct the editor to perform the final editing, 
      making sure to pass them the structure to follow and the prewritten texts (each with their identification), so they know how to organize.
      The final edit must:
        - Structure the chapter hierarchically using LaTeX (\section, \subsection, \subsubsection, etc.);
        - Ensure each text is allocated in its corresponding section or subsection;
        - Ensure NO CONTENT is summarized or altered during the final merge;
        - Follow the outline structure and order exactly.

      3. If revisions are necessary (flagged by the editor), interpret the issue, identify the problematic section/topic,
      and assign new research and writing tasks to fix the problem. Impose a maximum of 5 revision cycles. After the fifth, the chapter proceeds as-is.

      4. Once editing is complete, return the finalized chapter, making sure to clean up any thoughts or reports that the editor may have included in its response.

    **Restrictions:**
      - The chapter text must be written entirely in Brazilian Portuguese;
      - No section or subsection not specified in the outline may be added;
      - During the final editing phase, no content may be summarized or modified — only structured and placed.

    **Success Criteria:** 
      - The chapter follows the outline structure precisely;
      - All sections and subsections were properly assembled;
      - The final version is in LaTeX, fully structured and ready for publication;
      - Revisions were handled up to 5 times if needed.
  expected_output: >
    A complete chapter in LaTeX, structured according to the outline and containing:
    - Texts written with scientific foundation and clarity;
    - Proper LaTeX formatting using hierarchical commands;
    - Integration of previously written content without modifications;
    - Fluent transitions between sections.
  context: [research_and_write_sections]
