research_chapter_outline:
  description: >
    CHAPTER OUTLINE:

    {chapter_outline}

    Este capítulo é intitulado "{chapter_title}". Sua produção será dividida em duas etapas. Esta primeira task é responsável apenas pela 
    **pesquisa e estruturação argumentativa** com base no CHAPTER OUTLINE fornecido. A redação será feita em uma etapa posterior.

    **Processo de Execução:**
      1. **Analisar o outline completo**, identificando a estrutura hierárquica (seções, subseções) e os tópicos a serem abordados em cada item.

      2. Para **cada seção ou subseção** do outline (marcadas como "###", "####", etc.):
        * Para **cada tópico listado**:
          - Pesquisar artigos de referência que tratem do tema;
          - Extrair e resumir os principais argumentos, evidências, abordagens e consensos da literatura;
          - Organizar os achados em forma de blocos argumentativos claros, devidamente atribuídos ao tópico;
          - IMPORTANTE: DELEGUE A PESQUISA PARA O AGENTE `topic_researcher`.

      3. Consolidar os resultados da pesquisa em uma estrutura argumentativa organizada por seções, mantendo total correspondência com o outline.

    **Restrições:**
      - A pesquisa deve se basear em fontes acadêmicas (preferencialmente artigos científicos);
      - Não incluir textos redigidos como versão final — apenas os blocos argumentativos e evidências;
      - Não adicionar tópicos além dos que estão no outline.

    **Critérios de Sucesso:**
      - Todos os tópicos foram pesquisados e contextualizados;
      - As seções estão bem organizadas e com conteúdo suficiente para subsidiar a redação;
      - A estrutura segue fielmente a hierarquia e ordem do outline.

  expected_output: >
    Documento estruturado com base no outline, contendo:
    - Cada seção e subseção com seus respectivos tópicos;
    - Blocos argumentativos e evidências organizadas por tópico;
    - Nenhum texto redacional, apenas conteúdo bruto para uso na escrita.

write_and_edit_chapter:
  description: >
    CHAPTER OUTLINE:

    {chapter_outline}

    Este capítulo é intitulado "{chapter_title}". Você receberá o conteúdo argumentativo estruturado previamente pela task `research_chapter_outline`,
    que deverá ser transformado no capítulo final em LaTeX. Esta task inclui a **redação, edição, estruturação e consolidação do texto final**.

    **Processo de Execução:**
      1. **Para cada seção ou subseção** do outline (marcadas como "###", "####", etc.):
         - Redigir o texto com base nos blocos argumentativos correspondentes;
         - Garantir fluidez textual e boa transição entre tópicos;
         - Incluir menções contextualizadas a elementos visuais (sem transcrevê-los).

      2. Após escrever todas as seções:
         - Combinar os textos respeitando a estrutura do outline;
         - Formatar o capítulo em LaTeX, utilizando `\section`, `\subsection`, etc.;
         - Garantir que nenhuma parte do conteúdo seja perdida, resumida ou alterada na fusão final.

      3. Caso o agente *technical_editor* identifique problemas:
         - Localizar a seção/tópico problemático;
         - Corrigir com base no conteúdo da task anterior ou, se necessário, solicitar nova pesquisa;
         - Realizar no máximo 5 ciclos de revisão.

      4. Ao final do processo, retornar o capítulo finalizado ao usuário.

    **Restrições:**
      - O texto deve estar integralmente em português brasileiro;
      - Não alterar a estrutura ou ordem do outline;
      - Não adicionar novas seções ou tópicos além dos especificados.

    **Critérios de Sucesso:**
      - O texto segue fielmente o outline;
      - Todas as seções foram escritas com base em conteúdo previamente pesquisado;
      - O capítulo está escrito em português e formatado corretamente em LaTeX, pronto para ser incluído em um artigo científico.

  expected_output: >
    Capítulo completo em LaTeX, com:
    - Texto redigido com base nas evidências pesquisadas;
    - Estrutura hierárquica correta em LaTeX;
    - Menções adequadas a elementos visuais;
    - Transições claras e linguagem científica fluente.
  context: [research_chapter_outline]
