research_task:
  description: >
    Topicos de discussão:
    {discussion_topics}

    Analise os JSON contendo os tópicos de discussão da subseção "{section_title}" da seção "Resultados e Discussão" de um artigo científico, 
    tendo a certeza de:   
    1. Processar cada object presente no JSON array, passado em Topicos de discussao;
    2. Conduzir uma pequisa separada para cada chave presente no object, isto é, uma para "tópic", uma para "visual_elements_to_contextualize"
       (se existir) e outra para "numerical_results_to_contextualize" (se existir);

    Processo de execução da pesquisa (executar para cada item):
      - Extraia o termo-chave que melhor descreve o "tópic", "visual_elements_to_contextualize" ou "numerical_results_to_contextualize";
      - Execute sua ferramenta QueryArticlesTool, passando o termo-chave no parâmetro '\search_query\' e especificando corretamente o parametro '\doc_type\';
      - A partir do retornado, gere um texto de 1000+ palavras, com insights detalhados do item.
    
    Criterio para sucesso:
      - Todos os campos "tópic", "visual_elements_to_contextualize" e "numerical_results_to_contextualize" contidos nos tópicos de discussao foram pesquisados;
      - Os insights gerados são extremamente detalhados e conseguem ser utilizados para criar textos.
  expected_output: >
    Um objeto JSON contendo uma lista de insights detalhados, onde cada elemento da lista é um insight detalhado individual 
  
    Exemplo de saída:
    {
      "insights":["
        **Obtenção de Portas Lógicas**: A pesquisa apresenta o conceito e implementação de portas lógicas utilizando um
        acoplador em fibra óptica, onde é demonstrado que é possível extrair operações lógicas através desta estrutura
        única. Esta técnica utiliza a álgebra booleana para realizar cálculos, com as entradas podendo oscilar entre os
        valores 0 ou 1 lógicos.

        **Modelo Simbólico vs Real**: Os estudos literários destacam a viabilidade teórica da utilização de acopladores
        em fibra óptica para obter portas lógicas, mas a pesquisa apresenta um modelo prático e experimental com os
        resultados demonstrados no software implementando o método de Runge-Kutta.

        **Efeitos Lineares e Não-Lineares**: A literatura anterior aborda a modelagem dos efeitos lineares (dispersão
        de velocidade de grupo, variação desta dispersão) e não-lineares na fibra óptica (automodulação de fase,
        auto-inclinação, efeito Raman). A pesquisa apresenta esses mesmos efeitos como fatores relevantes no processo de
        modulação da entrada do pulso óptico.

        **Evolução das Comunicações Ópticas**: O Capítulo 1 do referido trabalho mostra um contexto histórico breve da
        evolução das comunicações ópticas, bem como a necessidade de desenvolvimento de dispositivos completamente ópticos
        e o surgimento da nova classe de fibras ópticas, a Fibra de Cristal Fotônico (PCF). A pesquisa se alinha com esta
        visão, destacando a importância do estudo físico das PCFs.

        **Efeitos Não-Lineares na PCF**: O Capítulo 3 do trabalho apresenta um estudo físico sobre os efeitos
        não-lineares na PCF e a derivação da equação de Schrödinger generalizada para aplicações em NLDC-PCF, mostrando
        como os acopladores podem ser usados neste contexto.
        "
      ]
    }
  agent: topic_researcher

write_section:
  description: >
    Com base no relatório de pesquisa e no outline original, escreva o conteúdo da seção (nível) do capítulo completo em português brasileiro,
    abordando TODOS os tópicos e subtópicos sem exceção.
    
    1. Siga rigorosamente a estrutura de seções e subseções definida no outline
    2. Incorpore as informações e referências do relatório de pesquisa para cada tópico
    3. Mantenha um estilo acadêmico-científico formal
    4. Escreva em português brasileiro claro e conciso
    5. Inclua sugestões para citações bibliográficas
    6. Garanta que absolutamente TODOS os tópicos e subtópicos listados no outline sejam abordados
        com profundidade adequada
    
    O texto deve ser acadêmico, fundamentado nas pesquisas e seguir rigorosamente o outline fornecido.
    Não negligencie nenhum tópico ou subtópico, independentemente de sua complexidade.
  expected_output: >
    Conteúdo textual completo da seção em português brasileiro que:
    1. Aborda todos os tópicos e subtópicos do outline sem exceção
    2. Segue exatamente a estrutura hierárquica definida no outline
    3. Incorpora adequadamente as informações da pesquisa
    4. Utiliza citações apropriadas no formato
    5. Mantém linguagem acadêmica e rigor científico
    6. Apresenta profundidade de conteúdo adequada para cada seção
    
    O texto deve estar pronto para formatação em LaTeX, com todas as seções e subseções
    claramente identificadas.
  agent: technical_writer

final_editing:
  description: >
    Faça a montagem final do capítulo em LaTeX adequado para documentos acadêmicos em português brasileiro,
    preservando integralmente todo o conteúdo e tendo a certeza de que todos os conteúdos textuais estão em 
    suas devidas seções(nível).
    
    1. Converta o texto completo para o formato LaTeX
    2. Estruture adequadamente todas as seções e subseções com comandos LaTeX apropriados
    3. Formate corretamente as citações bibliográficas
    4. Adicione comandos para numerar e referenciar tabelas e figuras se mencionadas
    5. Garanta que o texto esteja adequado para compilação em LaTeX
    6. Use pacotes necessários para suporte ao português brasileiro
    
    É ESSENCIAL que você preserve absolutamente todo o conteúdo original durante a formatação,
    sem omitir nenhuma parte do texto ou seção.
  expected_output: >
    Um documento LaTeX completo e pronto para compilação contendo:
    1. Estrutura completa do capítulo com todas as seções e subseções
    2. Todo o conteúdo do texto original preservado e formatado adequadamente
    3. Citações e referências no formato correto de LaTeX
    4. Formatação adequada para elementos como tabelas, figuras, equações, etc.
    5. Numeração adequada de seções e outros elementos conforme padrões acadêmicos
    
    O documento deve estar pronto para ser compilado em um sistema TeX sem necessidade de
    edições adicionais.
  agent: technical_editor
