write_technical_chapter:
  description: >
    CHAPTER OUTLINE:

    {chapter_outline}

    Generate the chapter "{chapter_title}" based on the provided CHAPTER OUTLINE, orchestrating its full production and text,
    delegating research, writing, and editing tasks to specialized subordinate agents. The resulting chapter must strictly follow 
    the proposed structure, be rich in content and arguments, formatted in LaTeX, and written in Brazilian Portuguese. All topics in each 
    section (or subsection, etc.) must be addressed.

    **Execution Process:**
      1. **Analyze the full outline**, identifying the hierarchical structure (sections, subsections), topics to be addressed in each,
      and visual elements to be included and contextualized.

      2. For **each section or subsection** in the outline (marked as "###", "####", etc.):
        * For **each topic** (bulleted items under each section):
          - Search reference articles for the topic and obtain the necessary arguments for writing.

        * After the research is done, write the section/subsection based on the outline and research findings.

      3. Once all sections are written, combine them according to the outline structure to form the complete chapter. Final editing must:
        - Structure the chapter hierarchically using LaTeX (`\section`, `\subsection`, `\subsubsection`, etc.);
        - Ensure no content is summarized or altered during the final merge;
        - Follow the outline structure and order faithfully;
        - Ensure all outline topics are covered in the chapter.

      4. If revisions are necessary (flagged by the *technical_editor* agent), interpret the issue, identify the problematic section/topic,
      and assign new research and writing tasks to fix the problem. Impose a maximum of 5 revision cycles. After the fifth, the chapter proceeds as-is.

      5. Once editing is complete, return the finalized chapter to the user. The task is complete.

    **Restrictions:**
      - The chapter text must be written entirely in Brazilian Portuguese;
      - During the final editing phase, no content must be summarized or modified, only placed in its correct position;
      - Do not add any section or subsection not specified in the outline.

    **Success Criteria:** 
      - The chapter follows the outline structure;
      - All subordinate agents were used in the task;
      - All topics were properly addressed and detailed;
      - The chapter is written in Brazilian Portuguese and formatted in fully functional LaTeX, ready for inclusion in a scientific article.
  expected_output: >
    A complete chapter in LaTeX, with text structured according to the outline, containing:
    - Paragraphs written with scientific foundation and argumentative clarity;
    - Contextual references to visual elements (without content transcription);
    - Correct use of hierarchical structure in LaTeX;
    - Textual fluency with clear transitions between topics and sections.
