write_technical_chapter:
  description: >
    OUTLINE DO CAPÍTULO:

    {chapter_outline}

    Coordene a criação do capítulo "{chapter_title}" a partir do OUTLINE DO CAPÍTULO fornecido, orquestrando a produção do capítulo e seu texto em completude, 
    delegando as atividades de pesquisa e escrita aos agentes subordinados especializados. Seu trabalho será executado de forma hierárquica, coordenando cada 
    tópico do outline individualmente através de um ciclo de **pesquisa + redação**, garantindo qualidade, profundidade e fidelidade à estrutura original, com
    o objetivo de, ao final do processo, obter um capítulo completo, escrito em LaTeX, em linguagem português brasileiro, abordando todas as seções e 
    tópico da estrutura proposta pelo OUTLINE, para um artigo científco de alto ímpacto.

    **Processo para execução da tarefa:**
    1. **Analise o outline completo**, identificando a estrutura hierárquica (seções, subseções), tópicos a tratar em cada uma delas e elementos visuais a serem
      incluídos como contextualização.

    2. Para **cada seção ou subseção** explicitada no outline (demarcadas por como "###", "####", etc.):
      * Para **cada tópico** da seção (pontos da lista logo a baixo ao título da seção, com cada elemento demarcado por "-", ex.:"- Compara os resultados..."):
        - Faça a pesquisa do tópico nos artigos de referencia e obtenha argumentação necessária para fundamentar a escrita do texto.

      * Após a conclusão da pesquisa, realize a escrita da seção ou subseção, levando em conta a estrutura pedida pelo outline e a argumentação obtida na fase
        de pesquisa.        

    3. Uma vez todas as seções e subseções escritas, combine-as de acordo com a estrutura para o capítulo explicitada no outline, da seguinte forma:
        - Organize-as em forma capítulo hierárquico em LaTeX, com uso adequado de `\section`, `\subsection`, `\subsubsection`, etc.;
        - Garanta transições suaves entre as partes para evitar fragmentação do capítulo;
        - Certificar-se de que a estrutura e a ordem do outline foram seguidas com fidelidade.

  expected_output: >
    Um capítulo completo em LaTeX, contendo:
    - Texto técnico estruturado com base no outline;
    - Parágrafos redigidos com fundamentação científica e clareza argumentativa;
    - Referências contextuais a elementos visuais (sem transcrição do conteúdo);
    - Uso correto de estrutura hierárquica em LaTeX;
    - Fluidez textual com transições claras entre tópicos e seções.
