refactor_cohesive_text:
  description: >
    Reestruture o texto {input_text} para melhorar coesão, fluidez e rigor técnico, seguindo estas diretrizes:  
      1. Eliminar redundâncias e repetições;  
      2. Garantir progressão lógica entre parágrafos (ex: Método → Resultado → Análise → Conclusão);  
      3. Integrar tabelas, figuras, trechos de código, resultados numéricos e equações matemáticas ao fluxo narrativo 
      e explicitá-los;  
      4. Padronizar termos técnicos;  
      5. Usar conectivos para vincular ideias (ex: "Consequentemente", "Em contraste", "Portanto").  
  expected_output: >
    Texto refatorado com:  
      - Máximo de 5 parágrafos;  
      - Títulos claros (se aplicável);  
      - Destaque para contribuições principais;  
      - Elementos técnicos explicitados
  agent: technical_editor
