critical_analysis:
  description: >
    Análise críticamente do conteúdo das chunks {chunk_indexes} do batch {batch_number} do documento {target_document},
    do tipo <type>'draft'</type>.    
    Escreva uma síntese crítica do conteúdo, contextualizada com o tema, em pelo menos um parágrafo. 
    O objetivo desta tarefa é produzir uma síntese crítica que sirva como base para a elaboração do capítulo de Resultados e Discussões.
    **Boas práticas para a escrita de síntese crítica:**
    - Utilize linguagem clara, objetiva e coerente;
      - Integre dados técnicos e argumentos principais de forma que evidencie como os métodos aplicados influenciam os resultados;
      - Contextualize as informações com o tema do documento;
      - Caso o conteúdo do batch apresente limitações (por exemplo, predominância de elementos não textuais), registre essa 
        limitação e indique a impossibilidade de uma análise crítica textual completa;
  expected_output: >
    Uma análise crítica do conteúdo do batch, escrita em português brasileiro, de pelo menos um parágrafo que sintetise
    criticamente o conteúdo, apresentando as principais informações, argumentos e dados, todos contextualizados com o tema,
    de forma clara e coesa.
  agent: critical_analyst

key_points_extraction:
  description: >
    Extraia e analise os pontos-chave e insights do conteúdo das chunks {chunk_indexes} do batch {batch_number} do documento {target_document}.
    O objetivo desta tarefa é identificar e destacar, em bullet points, os aspectos mais relevantes para a elaboração do capítulo.
    Siga as seguintes boas práticas:
      - Utiliza formatação Markdown para apresentar os pontos-chave de forma clara e concisa;
      - Organize as informações em bullet points, cada um contendo um insight ou comparação relevante;
      - Para cada bullet point, inclua um detalhamento explicativo que evidencie comparações (quando aplicável), inconsistências (ex: "Tabela ??")
        e a relação dos dados, métodos e informações com o tema;
      - Seja conciso, mas completo na explicação de cada ponto.
  expected_output: > 
    Uma lista de bullet points, escrita em português brasileiro, contendo os pontos-chave e insights extraídos, cada um acompanhado de um detalhamento
    explicativo que inclua comparações, contextualizações e destaques das inconsistências ou relações com o tema.
  context: [critical_analysis]
  agent: critical_analyst

methodology_analysis:
  description: >
    Analise as chunks {chunk_indexes} do batch {batch_number} do documento {target_document} (tema: {theme}). 
    O documento é do tipo <type>'draft'</type>.
    Faça uma analise da metodologia do conteúdo, verificando:    
    - A fundamentação teórica e justificativa para os métodos utilizados; 
    - A clareza, coerência e replicabilidade dos procedimentos descritos;  
    - Possíveis lacunas metodológicas ou pressuposições não explicitadas.
  expected_output: >
    Um texto estruturado abordando:
    1. Descrição e Avaliação dos Métodos Utilizados:
      - Explicação dos métodos aplicados e sua fundamentação teórica;
      - Avaliação da clareza na descrição dos procedimentos;
      - Verificação da coerência e replicabilidade.
    2. Identificação de Lacunas e Pressupostos:
      - Análise de possíveis inconsistências na metodologia;
      - Identificação de pressupostos metodológicos não explicitados.
  context: [key_points_extraction]
  agent: critical_analyst
  

results_analysis:
  description: >
    Analise as chunks {chunk_indexes} do batch {batch_number} do documento {target_document} (tema: {theme}). 
    O documento é do tipo <type>'draft'</type>.
    Avalie os resultados apresentados, considerando:
    
    - A consistência dos dados obtidos em relação aos objetivos e metodologia empregada;
    - A coerência das conclusões com base nas evidências apresentadas;
    - A presença de possíveis inconsistências, referências ausentes ou lacunas interpretativas.
  expected_output: >
    Um texto estruturado (mínimo um parágrafo) que contenha:
      - Uma avaliação da consistência dos dados apresentados em relação aos objetivos e à metodologia empregada.
      - Uma análise crítica da coerência das conclusões baseadas nas evidências (tabelas, métricas, resultados numéricos).
      - A identificação de inconsistências, referências ausentes ou lacunas interpretativas, como dados mal indexados ou ausentes (por exemplo, referência a "Tabela ??").
      - Sugestões de melhorias ou pontos a serem aprofundados, quando pertinente.
  context: [critical_analysis, methodology_analysis]
  agent: critical_analyst

elements_extraction: 
  description: >
    Extraia dados estruturados das chunks {chunk_indexes} (batch {batch_number}) do documento {target_document}, 
    seguindo regras rigorosas de formatação e padronização. O documento é do tipo <type>'draft'</type>
    Você deve coletar informações brutas e neutras (sem análise crítica) para posterior síntese, de dados chaves, 
    garantindo integridade e compatibilidade entre batches. Os dados chaves são:

       - **Resultados Numéricos**: Extrair valores, métricas e unidades explicitamente declarados (ex: "Eficiência: 85% ± 2%").
       - **Termos Técnicos**: Listar definições explícitas (ex: "Definição: 'Otimização Z' refere-se a...").
       - **Relações Declaradas**: Capturar conexões explícitas entre conceitos (ex: "Variável X correlacionada com Y (r=0.7)").
  expected_output: >
    Um relatório do batch, identificando documento e batch de chunk, formatado em markdown, apresentando os dados 
    chave encontrados e coletados em formato de lista. Caso não encontrados, informar isso.
  agent: technical_data_extractor

report_consolidation:
  description: >
    Utilizando a análise crítica, a análise metodológica, a análise de resultados e a extração de dados referentes
    ao lote de chunks {chunk_indexes} do batch {batch_number} do documento {target_document} (tema: {theme}), crie um relatório 
    consolidado. O relatório deve integrar e organizar os insights por relevância, apresentando um resumo executivo, os pontos 
    principais extraídos de cada análise e considerações finais. Deve ser formatado em markdown e conter identificação do documento 
    ao qual o relatório se refere ({target_document}) e qual o número do batch, no caso {batch_number}.
  expected_output: >
    Um relatório consolidado, escrito em português brasileiro, que inclua:
      - Identificação do documento e do batch ao qual o relatório se refer;
      - Um resumo executivo sintetizando as principais conclusões das análises;
      - Seções organizadas para cada área de análise (crítica, metodológica, de resultados e extração de dados), com os pontos-chave 
        e insights destacados;
      - Uma seção de considerações finais que integre os achados e aponte sugestões ou direções para a elaboração do capítulo de 
        Resultados e Discussões.
  context: [critical_analysis, methodology_analysis, results_analysis, elements_extraction]
  agent: report_redactor
  