critical_analysis:
  description: >
    Você irá trabalhar no conteúdo das chunks {chunk_indexes} do batch {batch_number} do documento {target_document},
    do tipo <type>'draft'</type>.

    Sua tarefa consiste em produzir uma análise crítica do conteúdo das chunks do batch, seguindo as orientações abaixo:
    
    1. Escreva uma síntese crítica do conteúdo, contextualizada com o tema, em pelo menos um parágrafo. A síntese deve 
    integrar dados técnicos, com as informações e argumentos principais, demonstrando como os métodos aplicados influenciam 
    os resultados.

    2. Extraia e analise pontos-chave e insights, apresentando-os em bullet points. Para cada bullet point, inclua:
       - Comparações relevantes, se aplicáveis (por exemplo, diferentes abordagens ou configurações apresentadas no documento).
       - Destaque de inconsistências ou referências incorretas (ex: "Tabela ??").
       - Relação dos dados, métodos e informações com o tema.
    
    Caso o conteúdo do batch apresente limitações (por exemplo, predominância de elementos não textuais), registre essa 
    limitação e indique a impossibilidade de uma análise crítica textual completa.
  expected_output: >
     Uma análise crítica do conteúdo do batch, escrita em português brasileiro, composta por:
      - Um parágrafo de síntese crítica e contextualização do tema.
      - Uma lista de bullet points contendo os pontos-chave e insights, cada um acompanhado de um detalhamento explicativo.
  agent: critical_analyst

methodology_analysis:
  description: >
    Analise as chunks {chunk_indexes} do batch {batch_number} do documento {target_document} (tema: {theme}). 
    O documento é do tipo <type>'draft'</type>.
    Faça uma analise da metodologia do conteúdo, verificando:    
    - A fundamentação teórica e justificativa para os métodos utilizados; 
    - A clareza, coerência e replicabilidade dos procedimentos descritos;  
    - Possíveis lacunas metodológicas ou pressuposições não explicitadas.
  expected_output: >
    Um texto estruturado abordando:
    1. Descrição e Avaliação dos Métodos Utilizados:
      - Explicação dos métodos aplicados e sua fundamentação teórica;
      - Avaliação da clareza na descrição dos procedimentos;
      - Verificação da coerência e replicabilidade.
    2. Identificação de Lacunas e Pressupostos:
      - Análise de possíveis inconsistências na metodologia;
      - Identificação de pressupostos metodológicos não explicitados.
  agent: critical_analyst

results_analysis:
  description: >
    Analise as chunks {chunk_indexes} do batch {batch_number} do documento {target_document} (tema: {theme}). 
    O documento é do tipo <type>'draft'</type>.
    Avalie os resultados apresentados, considerando:
    
    - A consistência dos dados obtidos em relação aos objetivos e metodologia empregada;
    - A coerência das conclusões com base nas evidências apresentadas;
    - A presença de possíveis inconsistências, referências ausentes ou lacunas interpretativas.
  expected_output: >
  context: [methodology_analysis]
  agent: critical_analyst

elements_extraction: 
  description: >
    Extraia dados estruturados das chunks {chunk_indexes} (batch {batch_number}) do documento {target_document}, 
    seguindo regras rigorosas de formatação e padronização. O documento é do tipo <type>'draft'</type>
    Você deve coletar informações brutas e neutras (sem análise crítica) para posterior síntese, de dados chaves, 
    garantindo integridade e compatibilidade entre batches. Os dados chaves são:

       - **Resultados Numéricos**: Extrair valores, métricas e unidades explicitamente declarados (ex: "Eficiência: 85% ± 2%").
       - **Termos Técnicos**: Listar definições explícitas (ex: "Definição: 'Otimização Z' refere-se a...").
       - **Relações Declaradas**: Capturar conexões explícitas entre conceitos (ex: "Variável X correlacionada com Y (r=0.7)").
  expected_output: >
    Um relatório do batch, identificando documento e batch de chunk, formatado em markdown, apresentando os dados 
    chave encontrados e coletados em formato de lista. Caso não encontrados, informar isso.
  agent: technical_data_extractor

critical_report_writing:
  description: >
    Utilize as analises realizadas para nas tarefas anteriores para escrever um relatório crítico do conteúdo do batch.
  expected_output:>
  context: [critical_analysis, methodology_analysis]