critical_analysis:
  description: >
    Realize uma análise crítica das chunks {chunk_indexes} (batch {batch_number}) do documento {target_document} (tema: {theme}), 
    que contém APENAS RESULTADOS PARCIAIS, sem seções introdutórias, metodológicas ou conclusivas. O documento é do tipo <type>
    'draft'</type>.

    Produza uma síntese crítica dos resultados apresentados no batch, avaliando sua clareza, relevância e possíveis lacunas.

    **Ações Obrigatórias**:
    1.  **Sintetizar e Avaliar:** Crie um resumo analítico e crítico do conteúdo, destacando pontos-chave, relações entre eles,
        e avaliando a qualidade da argumentação, relevância das evidências e clareza da exposição;
    2. **Mapeamento de Dependências**  
       - Registrar termos/conceitos que exigem contexto externo (ex: "Definição de 'Otimização Z' ausente");
    3. **Classificação de Relevância**  
       - Priorizar dados por potencial impacto na síntese final (ex: "Dados do chunk 5 são centrais para {theme}");
    4.  **Avaliar Elementos Complementares:** Analise o uso argumentativo de equações, códigos, tabelas, gráficos e figuras, que por
        ventura estejam presentes no texto das chunks (ex: "Os dados de 'tabela 1' são usados para").
    5.  **Identificar Limitações do Batch:** Se o conteúdo das chunks for predominantemente não textual (exemplo: apenas tabelas sem 
        explicação), registrar essa limitação, indicando a impossibilidade de uma análise crítica textual.
    
  expected_output: >
      Um Relatório do Batch, identificando o documento e a batch, apresentando uma **Síntese Crítica** com resumo contextualizado do 
      conteudo e os pontos-chaves, e sua relação com o tema; faça o mapeamento de dependências, registrando termos/conceitos que 
      exigem contexto externo

      **Inconsistências:**  
      - **Ambiguidade**: [Ex: "Termo 'alto desempenho' não quantificado (chunk 1)"]  
      - **Fragilidade Argumentativa**: [Ex: "Conclusão não sustenta evidências do Gráfico 2 (chunk 7)"]  

      **Alertas Técnicos:**  
      - [Ex: "Gráfico 1 (chunk 3) sem descrição de eixos"]  
      - [Ex: "Código no chunk 8 não documentado"]  

      **Problemas Textuais:**  
      - [Ex: "Repetição excessiva do termo 'otimização' sem definição (chunk 5)"]  
      - [Ex: "Estrutura passiva obscurece responsabilidade metodológica (chunk 2)"] 
  agent: critical_analyst

elements_extraction:
  description: >
    Extraia dados estruturados e elementos técnicos das chunks {chunk_indexes} (batch {batch_number}) do documento {target_document}, 
    seguindo regras rigorosas de formatação e padronização. O documento é do tipo <type>'draft'</type>
    Você deve coletar informações brutas e neutras (sem análise crítica) para posterior síntese, de elementos técnicos e dados chaves, 
    garantindo integridade e compatibilidade entre batches.

    **Ações Obrigatórias**:
    1. **Extrair Elementos Técnicos**:
       - **Tabelas**: Converter para HTML válido, mantendo cabeçalhos e dados brutos.
         - Exemplo: <table><tr><th>ID</th><th>Valor</th></tr><tr><td>1</td><td>42</td></tr></table>
       - **Equações**: Transcrever em LaTeX com contexto mínimo (ex: `E = mc^2`).
       - **Códigos**: Extrair trechos completos, indicando a linguagem (ex: ```python\nprint("Hello World")```).
       - **Gráficos/Imagens**: Registrar nome do arquivo, descrição textual e chunk de origem.

    2. **Coletar Dados Chave**:
       - **Resultados Numéricos**: Extrair valores, métricas e unidades explicitamente declarados (ex: "Eficiência: 85% ± 2%").
       - **Termos Técnicos**: Listar definições explícitas (ex: "Definição: 'Otimização Z' refere-se a...").
       - **Relações Declaradas**: Capturar conexões explícitas entre conceitos (ex: "Variável X correlacionada com Y (r=0.7)").

    3. **Metadados Contextuais**:
       - Registrar índices das chunks associadas a cada elemento.
       - Marcar termos/conceitos repetidos no batch (ex: "Termo 'Fator K' mencionado 5x").
  expected_output: >
    Um relatório do batch, identificando documento e batch de chunk, formatado em markdown, com uma seção apresentando os dados 
    chave encontrados e coletados, e outra contento: tabelas formatadas em HTML e funcional, trechos de código, equações e expressoes 
    matematicas, e figuras e gráficos, se encontrados no conteudo das chunks. Caso não, informar isso.
  agent: technical_data_extractor

