document_reading:
  description: >
    Sua tarefa é analisar o documento base: {target_document}
    Analise especificamente as chunks de índices:
    {chunk_indexes}

    Você deve utilizar a ferramenta FetchArticlesTool, tendo a certeza de especificar a lista de
    índices das chunks a serem analisadas.

    Faça a análise crítica das chunks, identificando o contexto e argumentos abordados, seus pontos
    principais; as evidências apresentadas, que podem ser em texto, tabelas, imagens e/ou resultados
    numéricos; a contribuição do conteúdo ao tema "{theme}"; e as limitações do texto.
    Você deve organizar seus achados em um relatório em formato JSON, indentificando qual documento
    base foi analisado e quais as chunks desse documento foram analisadas.
  expected_output: >
    Um relatório dissertativo-argumentativo detalhado, contendo todas as informações essenciais extraídas
    dos documentos base, com marcações claras, detalhamento dos principais pontos abordados, como
    também sujerindo pontos de melhora na estrutura, gramática e tom do texto, e como podem ser melhorados,
    além de pontos que requerem maior detalhamento e qual detalhamento, com as instruções de como estrutura-los
    de modo a criar a seção **Resultados e Discussão** de um artigo científico do tema {theme}.
  agent: reviewer
  tools: [FetchArticlesTool]