document_reading:
  description: >
    Você deve analisar chunks do documento: {target_document} 
    O tema do documento é: {theme} 
    Ele é documento do tipo <type>'draft'</type>. 
    Analise especificamente as chunks de índices: 
    {chunk_indexes} 

    Você deve utilizar a ferramenta FetchArticlesTool, tendo a certeza de especificar a lista de
    índices das chunks a serem analisadas, para ter acesso ao conteúdo do documento. 
    Junte os pedacos de conteudo dispostos no campo "content" de cada chunk em um único texto para
    iniciar sua analise.

    Então, você deve conduzir uma analise técnica detalhada do conteudo. Ademais, considere: 
    * Para equações e expressoes matematicas: Copie-as, escrevendo-as em formato LaTeX. 
    * Para tabelas: Copie a tabela na íntegra e converta-a para formato HTML válido.
      - As tabelas seguem o padrão identificado pelo regex: "(Tabela\s+\d+\s+\u2013\s+.*?\n(?:.*\n)+?)(?=Fonte:|$)"
      - Você deve transcreve-las em formato HTML completo e funcional, pronto para ser exibido diretamente em um navegador. 
      - Exemplo esperado: `<table><thead><tr><th>Coluna1</th><th>Coluna2</th></tr></thead><tbody><tr><td>Valor1</td><td>Valor2</td></tr></tbody></table>`.
    * Para graficos e imagens: capture o nome do objeto e a descricao dele que voce 
      encontrar no texto.
    * Para codigos: Copie o codigo na integra.
  expected_output: >
    Um relatorio detalhado e explicativo, da analise técnica do conteudo, perfeitamente estruturado em markdown, que sintetize o conteudo 
    e os elementos textuais, capturando a estrutura argumentativa do texto, seus pontos chaves e insights,
    elementos técnicos, e quaisquer pontos a mais.
  agent: reviewer
