document_reading:
  description: >
    Você deve analisar chunks do documento: {target_document} 
    O tema do documento é: {theme} 
    Ele é documento do tipo <type>'draft'</type>. 
    Analise especificamente as chunks de índices: 
    {chunk_indexes} 

    Você deve conduzir uma analise técnica detalhada e extensiva dos textos,
    de modo a extrair a extrutura textual, metodológica e argumentativa, se embasando em informações 
    complementares, tais como equações e expressões matemáticas, trechos de código, tabelas, gráficos e 
    figuras, explicitando suas influencias na argumentação dos textos.

    Você deve utilizar a ferramenta FetchArticlesTool, tendo a certeza de especificar a lista de
    índices das chunks a serem analisadas, para ter acesso ao conteúdo do documento. 
    Você não deve tratar o conteúdo das chunks como textos disconexos. Eles são partes que quando
    juntados formam uma seção, uma parcela, de um texto muito maior de mesmo tema. Não a toa,
    você está processando apenas um lote do total de chunks que esse documento foi dividido.
    Trate-os como tal.

    Ademais, considere: 
    * Para equações e expressoes matematicas: Copie-as, escrevendo-as em formato LaTeX. 
    * Para tabelas: Copie a tabela na íntegra e converta-a para formato HTML válido.
      - As tabelas seguem o padrão identificado pelo regex: "(Tabela\s+\d+\s+\u2013\s+.*?\n(?:.*\n)+?)(?=Fonte:|$)"
      - Você deve transcreve-las em formato HTML completo e funcional, pronto para ser exibido diretamente em um navegador. 
      - Exemplo esperado: `<table><thead><tr><th>Coluna1</th><th>Coluna2</th></tr></thead><tbody><tr><td>Valor1</td><td>Valor2</td></tr></tbody></table>`.
    * Para graficos e imagens: capture o nome do objeto e a descricao dele que voce 
      encontrar no texto.
    * Para codigos: Copie o codigo na integra.
  expected_output: >
    Uma analise técnica do conteudo em forma de relatorio, detalhado e extensivo, perfeitamente estruturado em markdown, 
    que capture o conteudo, os elementos textuais e a estrutura argumentativa do texto, além de seus pontos-chaves e insights,
    que conecta os resultados ao propósito do texto.    
  agent: reviewer
