initial_assessment:
  description: >
    Sua tarefa é analisar o(s) documento(s) base: {document_list}
    Você deve gerar um relatório de análise de ambos os documentos, extremamente detalhado,
    de acordo com as suas diretrizes, e instruções de como junta-los em um só texto. Texto
    esse que será a seção **Resultados e Discussão** de um artigo ciêntífico do tema {theme}.

  expected_output: >
    Um relatório dissertativo-argumentativo detalhado, contendo todas as informações essenciais extraídas
    dos documentos base, com marcações claras, detalhamento dos principais pontos abordados, como
    também sujerindo pontos de melhora na estrutura, gramática e tom do texto, e como podem ser melhorados,
    além de pontos que requerem maior detalhamento e qual detalhamento, com as instruções de como estrutura-los
    de modo a criar a seção **Resultados e Discussão** de um artigo científico do tema {theme}.
  agent: analyst
#
#query_process:
#  description: >
#    Leia os documentos base e levante questionamentos sobre os eles, buscando identificar lacunas, inconsistências ou
#    pontos que podem ser aprofundados no texto e resultados apresentados pelos documentos base. Uma vez identificados,
#    busque responde-los, preenchendo e aprofundando a discussão do texto base.
#    que ampliem a discussão(ex.: “análise comparativa de [resultado específico]”, “discussões sobre [aspecto] na literatura”)
#    .
#    Em seguida, sintetize as informações obtidas em respostas integradas que enriqueçam a discussão, referenciando os metadados dos trechos consultados.
#  expected_output: >
#    Um relatório estruturado em formato JSON que, para cada lacuna ou ponto a ser aprofundado, contenha:
#    - A query utilizada;
#    - As referências (metadados dos artigos e trechos extraídos);
#    - Uma resposta sintetizada que integra os achados com o contexto da discussão.
#    
#    Exemplo de estrutura:
#    {
#      "<ponto/lacuna>": {
#        "query": "<query gerada>",
#        "referências": [
#          { "título": "<título do artigo>", "autor": "<nome do autor>", "ano": "<ano>", "link": "<URL>" },
#          ...
#        ],
#        "resposta": "<resposta sintetizada>"
#      }
#    }
#  agent: researcher
#
#query_generation:
#  description: >
#    Utilize as informações extraídas para formular queries que não só busquem resultados similares,
#    mas também ampliem e complementem a discussão existente.
#    Identifique lacunas ou pontos que podem ser aprofundados na discussão (por exemplo, inconsistências, 
#    tendências inesperadas ou temas controversos). Gerar variações de queries, explorando diferentes ângulos,
#    tais como “análise comparativa de [resultado específico]” ou “discussões sobre [aspecto] na literatura”.
#  expected_output: >
#    Uma representação estruturada no formato JSON contendo mapeando a query gerada para qual lacuna ou 
#    ponto ela ataca e/ou aprofunda, dessa maneira: <ponto/lacuna a ser aprofundada>: <query gerada>   
#  agent: analyst
#
#query_execution:
#  description: >
#    Sua tarefa é receber as queries geradas pelo agente analista e executar buscas na biblioteca de artigos.
#    Para cada query, utilize a ferramenta QueryArticlesTool para localizar artigos relevantes e recuperar os
#    trechos essenciais que respondam à demanda. Em seguida, sintetize essas informações para gerar respostas
#    integradas, realizando uma abordagem de Retrieval-Augmented Generation (RAG) que aprofunde a discussão.
#    Caso ache necessário, você pode gerar novas queries, se ainda houver necessidade de maior contexto.
#  expected_output: >
#    Um relatório estruturado em formato JSON contendo, para cada ponto/lacuna a ser aprofundada, uma referência
#    com os metadados dos trechos utilizados e sua resposta sintetizada que integra os achados com o contexto da
#    discussão. A estrutura deve seguir esse formato: 
#    "<ponto/lacuna a ser aprofundada>: "referências": [<metadados1>,...<metadadosN>], "resposta": "resposta sintetizada""
#  agent: researcher
#
#generate_outline:
#  description: >
#    Sua tarefa é criar um esboço detalhado da seção de "Resultados e Discussão", utilizando as informações
#    extraídas dos documentos base (initial_assessment) e as respostas obtidas pelo pesquisador (query_execution).
#    O outline deve ser estruturado em duas partes principais — Resultados e Discussão — e apresentar, em formato
#    JSON, os tópicos e subtópicos que comporão essa seção. O esboço deve detalhar o que deve ser escrito, informando
#    explicitamente que:
#    
#    - Na parte de **Resultados**: o autor deverá apresentar os dados relevantes de forma objetiva, lógica e concisa;
#      deve destacar os resultados mais importantes, organizar os dados em seções, incluir as características dos sujeitos do
#      estudo, expor achados secundários ou inesperados, relatar resultados negativos importantes e sugerir o uso de
#      ilustrações (como tabelas e figuras). Esses dados são oriundos da análise dos documentos base (initial_assessment).
#    
#    - Na parte de **Discussão**: o autor deverá realçar os achados relevantes e originais, avaliar criticamente a própria
#      pesquisa, comparar os resultados com a literatura pertinente, interpretar os achados e concluir com generalizações,
#      implicações, perspectivas e recomendações, além de comentar sobre o significado dos resultados e expressar sua posição
#      sobre o assunto. Nesta seção, os insights e referências extraídos pelo pesquisador (query_execution) devem ser
#      integrados para enriquecer a discussão.
#      
#    Seu output deve ser um JSON que sirva de guia para a redação final da seção, sem extrapolar para outras partes do trabalho.
#    Ele deve incluir descrições de imagens, além de tabelas estraídas das referências, se aplicável.
#
#  expected_output: >
#    Um JSON estruturado que defina os tópicos e subtópicos da seção "Resultados e Discussão". O output deverá ter o seguinte formato:
#    ```json
#    {
#      "Resultados e Discussão": {
#        "Resultados": {
#          "objetivo": "Apresentar os dados relevantes de forma objetiva, lógica e concisa.",
#          "detalhamento": "Destacar os resultados mais importantes, organizar os dados em seções, incluir características dos sujeitos do estudo, expor achados secundários relevantes ou inesperados, relatar resultados negativos importantes e indicar o uso de ilustrações (tabelas e figuras).",
#          "fonte": "Resultados do autor provenientes da análise inicial (initial_assessment)."
#          "imagens pertinentes": "descrição de imagens a serem utilizadas nos resultados".
#          "tabelas": "Tabelas extraídas das referências, uteis para a apresentação e compreensão dos resultados"
#        },
#        "Discussão": {
#          "objetivo": "Discutir os resultados apresentados, avaliando criticamente a própria pesquisa e comparando com a literatura pertinente.",
#          "detalhamento": "Realçar os achados relevantes e originais, interpretar os resultados, comparar com outros achados da literatura, e concluir com generalizações, implicações, perspectivas e recomendações, além de comentar sobre o significado dos resultados e expressar a posição do autor.",
#          "fonte": "Insights e referências provenientes do pesquisador (query_execution)."
#          "imagens pertinentes": "descrição de imagens a serem utilizadas nas discussões".
#          "tabelas": "Tabelas extraídas das referências, uteis para a apresentação, compreensão e comparação entre os resultados das referencias e do estudo"
#        }
#      }
#    }
#    ```
#  agent: analyst
#  context: [initial_assessment, query_execution]
#
#compose_section:
#  description: >
#    Sua tarefa é elaborar um texto dissertativo final para a seção de "Resultados e Discussão", utilizando os contextos, outlines e
#    informações armazenadas pelos agentes anteriores em suas tarefas (initial_assessment, generate_outline e query_execution). O texto deve ser
#    argumentativo, coeso e estruturado, e apresentar de forma clara o conteúdo que será inserido na seção do artigo. Para isso,
#    divida o texto em duas partes principais:
#
#    **Seção de Resultados:**
#      - Apresentar os dados relevantes de forma objetiva, lógica e concisa.
#      - Destacar os resultados mais importantes.
#      - Organizar os resultados em seções, conforme a análise dos dados.
#      - Incluir características dos sujeitos do estudo.
#      - Expor achados secundários relevantes ou inesperados.
#      - Relatar resultados negativos importantes.
#      - Sugerir o uso de ilustrações, como tabelas e figuras, para resumir informações.
#
#    **Seção de Discussão:**
#      - Realçar os achados relevantes e originais.
#      - Avaliar criticamente a própria pesquisa.
#      - Comparar os resultados com a literatura pertinente.
#      - Interpretar os achados de forma aprofundada.
#      - Concluir com generalizações, implicações, perspectivas e recomendações.
#      - Comentar sobre o significado dos resultados e a posição do autor.
#
#    Utilize os outlines e guias fornecidos para compor um texto final que possa ser incorporado diretamente ao artigo,
#    focando exclusivamente nessa seção.    
#  expected_output: >
#    Um texto dissertativo-argumentativo final, sem numeração, que apresente a seção "Resultados e Discussão" de forma coesa e detalhada.
#    O texto deve conter duas partes claramente definidas:
#
#    - **Na parte de Resultados:** deve ser feita a apresentação dos dados relevantes, organizando-os em seções, destacando os
#      resultados principais e secundários, mencionando as características dos sujeitos do estudo, relatando eventuais resultados
#      negativos. Você deve incluir imagens e tabelas.
#    
#    - **Na parte de Discussão:** deve ser feita a análise crítica dos resultados, a comparação com a literatura, a interpretação dos
#      achados e a apresentação de conclusões com implicações, perspectivas e recomendações, integrando os insights extraídos pela
#      ferramenta de pesquisa. Você pode incluir imagens e tabelas.
#
#  agent: writer
#  context: [initial_assessment, generate_outline, query_execution]