analyze_report_for_conclusion:
  description: >
    **Analytical Report**:

    {report}

    Analyze the provided analytical report to extract key interpretive content, implications, limitations, and
    contributions relevant for generating a structured outline for the "Conclusion" section of a scientific paper.
    Focus exclusively on sections 3 (Critical Interpretation), 4 (Evaluation of Study Limitations), and 5 (Contributions)
    of the report to identify insights directly supporting the study's final statements.

    **Inputs**:
    - Analytical report with the following five sections:
      1. Apresentação Clara dos Elementos Visuais (Presentation of Visual Elements)
      2. Análise dos Resultados (Analysis of Results)
      3. Interpretação Crítica (Critical Interpretation)
      4. Avaliação das Limitações do Estudo (Evaluation of Study Limitations)
      5. Contribuições (Contributions)

    **Execution Steps**:
    1. Review sections 3, 4, and 5 of the **Analytical Report** to identify:
      - Interpretations and literature comparisons or gaps (section 3) that inform the study's implications.
      - Major implications and contributions (section 5).
      - Key limitations (section 4).
      - Future research directions (sections 4 and 5).
    2. Write a structured text summary in Markdown with:
      - **Major Implications/Contributions**: A concise description of 1-2 significant impacts or contributions identified in section 5.
      - **Key Limitations**: A concise description of 1-2 important constraints identified in section 4.
      - **Future Research Highlights**: Proposed 1-2 key next steps or directions for research identified in sections 4 and 5.
      - **Interpretive Insights for Conclusion**: Summarize key interpretive points from section 3 that provide overarching context for the study's conclusions, ensuring it complements the contributions.

    **Guidelines**:
    - **Focus**: Exclusively on content from sections 3, 4, and 5 of the analytical report.
    - **Conciseness**: Summarize points effectively for a conclusion.
    - **Objectivity**: Maintain an objective and summary-focused tone.
    - **Traceability**: All extracted content must be directly verifiable within the specified sections of the analytical report.

    **Restrictions**:
    - Do not invent data or add external information.
    - Do not perform detailed interpretations or comparisons to literature; focus on summarizing implications, contributions, limitations, and future directions as stated in the report.
    - Do not include content from "Results" outline or any other generated sections.

    **Success Criteria**:
    - Delivers a structured text summary in Markdown format with major implications/contributions, key limitations, future research highlights, and interpretive insights for conclusion.
    - Grounds content solely in report sections 3, 4, and 5.
    - Suitable for generation of a structured outline for the "Conclusion" section.
  expected_output: >
    ```markdown
    **Conclusion Analysis Summary from Report**:

    - **Major Implications/Contributions**: Descrição concisa de 1-2 impactos/contribuições significativas extraídas da seção 5 do relatório.
    - **Key Limitations**: Descrição concisa de 1-2 limitações importantes extraídas da seção 4 do relatório.
    - **Future Research Highlights**: Propostas concisas de 1-2 próximos passos ou direções de pesquisa extraídas das seções 4 e 5 do relatório.
    - **Interpretive Insights for Conclusion**: Resumo conciso de pontos interpretativos chave da seção 3 do relatório que fornecem contexto geral para as conclusões do estudo.
    ```
  agent: report_analyst

analyze_generated_sections_for_conclusion_context:
  description: >
    **Generated Section Contents:**
    {generated_sections_content}

    Analyze the provided content from previously generated sections (Results and Discussion) to extract and summarize
    key interpretive content, implications, limitations, and contributions that are essential for shaping the
    "Conclusion" section. The goal is to identify how specific findings were interpreted, discussed, or how their
    implications were elaborated in relation to the study's overall message. This task ensures the conclusion
    is consistent with the preceding detailed sections.

    **Input Detailing**:
    - **Generated Section Contents**: A JSON list containing objects for each previously generated section. Each object has:
      - `section_name` (string): The name of the section (e.g., "Resultados e Discussão").
      - `topics_content` (list of objects): A list of objects, each containing:
        - `topic` (string): The name of the specific topic.
        - `text_content` (string): The generated text content for that topic.

    **Execution Steps**:
      1. Iterate through each `section_name` and its `topics_content` in `generated_sections_content`.
      2. For each `topic` and its `text_content` within the "Resultados e Discussão" section:
         - Identify any elaborated interpretations of findings.
         - Extract discussions of implications or significance of results.
         - Note any limitations discussed in the context of specific findings.
         - Identify any contributions or novel aspects highlighted within the discussion of results.
         - Pay attention to how the findings presented in the "Results" part lead to the interpretations in the "Discussion" part of the combined section.
      3. Synthesize the identified contextual information into a structured Markdown summary. Organize by section and then by topic,
         highlighting the most relevant interpretive and conclusive insights derived from the detailed discussion.

    **Guidelines**:
      - **Contextual Focus**: Emphasize how findings were interpreted, what their implications are, and any limitations or contributions *as discussed in the generated text*.
      - **Traceability**: All extracted information must be directly attributable to the `text_content` of the input sections.
      - **No Redundancy**: Avoid simply re-summarizing factual findings already covered in the `analyze_report_for_conclusion` task; focus on their *interpretation and implications*.
      - **Clarity**: Ensure the summary clearly outlines the interpretive context provided by the generated text.

    **Restrictions**:
      - Do not invent interpretations, implications, or limitations.
      - Do not summarize the methods; this task is about the *meaning* derived from the findings.
      - Do not generate prose or narrative beyond structuring the summary; output must be structured Markdown.
      - Only consider content from "Resultados e Discussão".

    **Success Criteria**:
      - Returns a Markdown formatted text containing a comprehensive and structured summary of interpretive content, implications, limitations, and contributions derived from the generated "Resultados e Discussão" section.
      - The summary is organized by section and topic, providing specific insights into how findings were interpreted and their significance.
  expected_output: >
    ```markdown
    # Contexto Interpretativo das Seções Geradas para a Conclusão

    ## Resultados e Discussão

    ### Tópico: Interpretação dos Dados de Eficiência
    - **Contexto para Conclusão**: A análise da eficiência do sistema (discutida em relação à Figura X e Tabela Y) revelou que a otimização via [Método de Otimização] resultou em uma melhoria de 15% na performance, o que implica uma aplicabilidade promissora em ambientes de baixa energia. Este ponto é crucial para a conclusão, pois valida a principal contribuição do estudo.

    ### Tópico: Discussão das Implicações Ambientais
    - **Contexto para Conclusão**: As discussões sobre o baixo impacto ambiental do material [Material Z], conforme detalhado neste tópico, indicam uma contribuição significativa para o desenvolvimento sustentável de novas tecnologias. Esta implicação deverá ser salientada na conclusão como um dos principais achados do estudo.

    ### Tópico: Limitações na Escalabilidade do Protótipo
    - **Contexto para Conclusão**: A dificuldade de replicar os resultados em larga escala devido às limitações do equipamento de laboratório [Nome do Equipamento] foi explicitamente abordada. Essa limitação é fundamental para a seção de Conclusão, pois molda as direções de pesquisa futura e tempera o escopo das aplicações imediatas.
    ```
  agent: report_analyst

structure_conclusion_outline:
  description: >
    "Convert the structured conclusion analysis summary from the analytical report and the methodological/interpretive context
    derived from generated sections into a full outline for the "Conclusion" section of a scientific paper. This task extracts
    key summary points (3-5) from the analyzed content and then structures them logically for the conclusion section, guiding a
    Writer Agent to produce a concise narrative that summarizes findings, highlights implications, mentions limitations,
    and suggests future work.

    **Inputs**:
    - **Conclusion Analysis Summary from Report**: Structured text summary from `analyze_report_for_conclusion`.
    - **Context from Generated Sections**: Markdown formatted text from `analyze_generated_sections_for_conclusion_context`.

    **Execution Steps**:
    1. Parse the summary from `analyze_report_for_conclusion` to identify key implications/contributions, limitations, future directions, and interpretive insights.
    2. Parse the summary from `analyze_generated_sections_for_conclusion_context` to understand how the findings were discussed and interpreted, and how they relate to the overall message.
    3. Synthesize the information from both inputs to identify 3-5 distinct points for the conclusion outline, ensuring a logical flow typical for a conclusion:
        - Start with a concise synthesis of key findings (informed by the `analyze_generated_sections_for_conclusion_context`).
        - Follow with major implications and contributions (from both inputs).
        - Acknowledge key limitations (from both inputs).
        - End with proposed future research (from both inputs).
    4. For each conclusion point:
      - Create `topic`: concise title (e.g., "Síntese dos Principais Achados", "Implicações e Contribuições").
      - Define `rhetorical_purpose` (e.g., "Synthesize findings", "Highlight contributions", "Acknowledge limitations", "Propose future research").
      - Write `topic_description`: brief summary of the point's focus, integrating insights from both analysis tasks.
      - Write `narrative_guidance`: clear, actionable instruction for the writer (e.g., "Comece sintetizando os resultados mais importantes e o que eles significam no contexto do estudo, utilizando os insights da discussão.").

    **Guidelines**:
    - Maintain a concise and concluding tone.
    - Ensure logical flow of points within the conclusion outline.
    - Base content solely on the analysis summaries; do not introduce external information.
    - Limit to 3-5 points for conciseness and impact.

    **Restrictions**:
    - Do not perform detailed interpretations or comparisons to literature.
    - Do not invent new data or claims.
    - Do not include long narrative; guidance only.
    - The `expected_output` must be a JSON with a specific structure.

    **Success Criteria**:
    - Returns a JSON with:
      - `subsection_name`: "Conclusion"
      - `conclusion_topics`: list of 3-5 items, each with:
        - `topic`
        - `rhetorical_purpose`
        - `topic_description`
        - `narrative_guidance`
    - The outline is comprehensive, logically structured, and directly derived from the provided analysis summaries.

  expected_output: >
    A structured outline for the "Conclusion" section to guide the Writer Agent in producing a detailed, objective narrative. The output must include:
    - `subsection_name`: Set to "Conclusion"
    - `conclusion_topics`: A list of 3-5 items, each containing:
      - `topic`: Concise title of the conclusion point.
      - `rhetorical_purpose`: The topic's rhetorical purpose (e.g., "Synthesize findings", "Highlight contributions").
      - `topic_description`: Brief summary of the point's focus and key information.
      - `narrative_guidance`: Clear instructions to guide the Writer Agent.

  agent: conclusion_outliner
  context: [analyze_report_for_conclusion, analyze_generated_sections_for_conclusion_context]

