generate_outline_results_discussion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo **Resultados e Discussão** de um artigo científico, com base no relatório analítico consolidado. 
    O outline deve funcionar como um plano técnico e hierárquico, destinado a orientar um agente inteligente redator na construção do capítulo. 
    O objetivo é garantir que a posterior redação ocorra com alta fidelidade lógica, estrutural e analítica, a partir de instruções precisas e 
    interpretáveis por máquina, dessa forma, fornecendo suporte à escrita científica automatizada com elevado grau de coesão, rastreabilidade
    e fidelidade aos dados e análises extraídas de documentos técnicos.

    **Processo para execução da tarefa:**
      * Interprete o relatório analítico consolidado como sua única fonte de verdade;
      * Estruture o outline em três blocos principais:
        1. **Introdução**: contextualização do capítulo e dos resultados que serão apresentados.
        2. **Resultados**: organização dos principais achados conforme a sequência metodológica ou lógica das perguntas de pesquisa. Para cada tópico:
            - Defina um título representativo;
            - Descreva o foco argumentativo;
            - Relacione-o com os dados da seção "Análise dos Resultados";
            - Indique os elementos visuais relacionados, com uma breve nota funcional (ex: *"Figura 3: Evidencia a melhoria do contraste óptico após 
              otimização."*).
        3. **Discussão**: tópicos interpretativos baseados nas seções "Interpretação Crítica", "Limitações" e "Contribuições". Inclua subtópicos com 
           os seguintes focos:
            - Relação com a literatura existente;
            - Implicações teóricas;
            - Limitações do estudo;
            - Contribuições científicas.

    **Restrições:**
      * Não redigir o texto do capítulo, apenas sua estrutura com instruções descritivas e funcionais;
      * Não utilizar fontes externas ao relatório;
      * Não modificar a estrutura base (Introdução / Resultados / Discussão);

    **Diretrizes para geração bem sucedida:**
      * O outline segue integralmente a estrutura especificada;
      * Todos os tópicos estão diretamente ancorados em seções do relatório;
      * Os elementos visuais estão contextualizados com função comunicativa clara;
      * A saída está pronta para ser consumida por outro agente inteligente sem necessidade de reinterpretação manual.
  expected_output: |
    Um outline para o capítulo **Resultados e Discussão** de um artigo científico, ancorado no relatório analítico consolidado, 
    composto por um texto em três níveis hierárquicos: Títulos principais (seções); Tópicos e subtópicos (subseções) com: Título conciso; 
    Descrição funcional orientando o foco da escrita; Indicação dos elementos visuais relevantes e sua função.

    Exemplo de saída:
     ## Resultados e Discussão

    ### Introdução
    - Apresenta o propósito do capítulo e o escopo dos dados que serão analisados.

    ### Resultados

    #### 1. Desempenho do Algoritmo Genético
    - Apresenta os padrões de convergência e estabilidade obtidos nas simulações.
    - **Elemento visual:** Figura 4 - Representa o progresso do fitness ao longo das gerações.

    #### 2. Validação da Porta OR
    - Demonstra o comportamento esperado da lógica OR nas cinco entradas, validado por Tabela 2.
    - **Elemento visual:** Tabela 2 - Mostra os estados de entrada e saída conforme esperado.

    ### Discussão

    #### 1. Relação com Trabalhos Anteriores
    - Compara os resultados obtidos com soluções propostas na literatura.

    #### 2. Implicações Teóricas
    - Analisa o impacto do uso de AGs na modelagem fotônica.

    #### 3. Limitações do Estudo
    - Aponta ausência de repetição de simulações e validação experimental.

    #### 4. Contribuições
    - Destaca a redução de complexidade e o potencial da metodologia para lógica óptica integrada.
  agent: core_chapters_outliner

generate_outline_conclusion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo de **Conclusão** de um artigo científico, com base no relatório analítico consolidado
    e no outline previamente gerado para o capítulo de Resultados e Discussão, criado na tarefa anterior, generate_outline_results_discussion.
    O objetivo do outline é fornecer uma estrutura lógica e funcional que será utilizada por um agente inteligente redator para construir o texto 
    final do capítulo. A conclusão deve sintetizar os principais achados do estudo, refletir sobre suas limitações e destacar as contribuições 
    científicas e técnicas da pesquisa. Esse plano textual deve permitir que o redator construa um encerramento forte, coeso e tecnicamente fundamentado.

    **Processo para execução da tarefa:**
      * Analise os tópicos abordados no outline de Resultados e Discussão para garantir continuidade lógica com o conteúdo anterior.
      * Utilize a seção **Interpretação Crítica** para sintetizar as conclusões mais relevantes a partir das evidências discutidas.
      * A partir da seção **Avaliação das Limitações do Estudo**, elabore tópicos que reconheçam as fragilidades metodológicas ou escopos restritos.
      * Com base na seção **Contribuições**, crie tópicos que destaquem os méritos científicos, metodológicos ou tecnológicos do estudo.
      * Quando pertinente, inclua um tópico final com **perspectivas para trabalhos futuros**, desde que fundamentado no relatório.

    **Restrições:**
      * O outline não deve conter trechos redacionais nem repetir texto do capítulo anterior.
      * Não deve extrapolar ideias ou propor novas interpretações além do que está contido no relatório.
      * A estrutura do capítulo deve seguir a lógica: síntese dos achados → limitações → contribuições → perspectivas (opcional).

    **Diretrizes para geração bem sucedida:**
      * O outline cobre os três elementos essenciais de uma conclusão (síntese, limitações, contribuições);
      * Os tópicos estão fundamentados nas seções corretas do relatório;
      * O encadeamento textual proposto reflete fechamento, não desenvolvimento de ideias inéditas;
      * A saída é clara, interpretável por outro agente, e permite continuidade coesa com o capítulo anterior.
  expected_output: |
    Um outline para o capítulo **Conclusão** de um artigo científico, ancorado no relatório analítico consolidado e coeso com o abordado 
    no capítulo de Resultados e Discussão, que cubra os três elementos essenciais de uma conclusão (síntese, limitações, contribuições), 
    composto por um texto em três níveis hierárquicos: Título da seção; Tópicos com títulos descritivos e descrições orientativas; Organização 
    sequencial coerente com a função de encerramento do artigo.

    Exemplo de saída:
    ## Conclusão

    ### 1. Síntese dos Principais Resultados
    - Retoma os achados mais relevantes do capítulo anterior e reafirma a viabilidade da porta lógica OR multientrada com base na modelagem via AG.

    ### 2. Limitações do Estudo
    - Discute restrições como a ausência de validação experimental e a dependência de uma única execução do algoritmo.

    ### 3. Contribuições Técnicas e Científicas
    - Destaca avanços como a redução de elementos ópticos, o uso eficiente do AG no design fotônico e a aplicabilidade da abordagem a outras portas.

    ### 4. Perspectivas para Trabalhos Futuros
    - Aponta possíveis caminhos como a criação de portas AND, XOR, ou sistemas fotônicos integrados de maior escala.
  agent: core_chapters_outliner
  context: [generate_outline_results_discussion]

generate_outline_methodology:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo **Metodologia** de um artigo científico, com base no relatório analítico consolidado (report), 
    e nos outlines previamente gerados para os capítulos de Resultados e Discussão (results_discussion_outline) e Conclusão (conclusion_outline).
    O objetivo da tarefa é construir um plano técnico e hierárquico que permita a um agente inteligente redator compor o capítulo de Metodologia 
    com base nos procedimentos, abordagens e critérios inferidos a partir da análise do estudo. O outline deve deixar claro o que foi feito, como 
    foi feito, e com que objetivos operacionais.

    **Processo para execução da tarefa:**
      * Examine os resultados descritos no report e no outline de Resultados e Discussão para inferir quais métodos foram utilizados;
      * Utilize as informações da seção **Apresentação Clara dos Elementos Visuais** para identificar fluxogramas, diagramas, equações e 
        representações gráficas associadas ao procedimento metodológico;
      * Use a seção **Interpretação Crítica** para identificar decisões de projeto relevantes e justificativas metodológicas que devem aparecer na 
        estrutura do capítulo;
      * A partir da **Avaliação das Limitações do Estudo**, identifique pontos que devem ser abordados explicitamente como limitações do método;
      * Consulte a seção de **Contribuições** para estruturar um tópico final destacando os diferenciais da metodologia utilizada.

    **Restrições:**
      * Não incluir trechos redacionais ou narrativas descritivas;
      * Não alterar a ordem dos procedimentos inferidos do relatório;
      * A metodologia deve ser estruturada como processo reprodutível: do início ao fim da execução experimental ou computacional;
      * Não extrapolar a partir do domínio do relatório — apenas descrever o que foi aplicado ou justificado no documento.

    **Diretrizes para geração bem sucedida:**
      * O outline cobre os principais blocos do método (entrada, processamento, saída);
      * A ordem dos tópicos reflete o fluxo metodológico do estudo;
      * Há referência explícita a elementos visuais de suporte técnico (fluxogramas, equações, diagramas);
      * O conteúdo é suficiente para permitir que outro agente redator gere um capítulo completo, técnico e reprodutível.
  expected_output: |
    Um outline para o capítulo **Metodologia** de um artigo científico, ancorado no relatório analítico consolidado e coeso com o abordado 
    nos capítulos de Resultados e Discussão, e Conclusão, composto por um texto estruturado por seções e subtópicos contendo: Títulos 
    representando fases metodológicas; Descrições orientativas de como redigir cada parte; Indicação de elementos visuais com função 
    operacional clara.

    Exemplo de saída:
    ## Metodologia

    ### 1. Formulação do Problema
    - Apresenta a necessidade de projetar uma porta lógica OR de cinco entradas com base em modelagem geométrica.
    - **Elemento visual:** Figura 1 - Esquema conceitual da estrutura fotônica desejada.

    ### 2. Definição dos Parâmetros de Projeto
    - Explica os parâmetros de entrada considerados (largura dos núcleos, espaçamento, angulação).
    - **Elemento visual:** Tabela 1 - Lista de parâmetros ajustáveis usados como input no algoritmo.

    ### 3. Implementação do Algoritmo Genético
    - Descreve a estrutura do algoritmo, operadores utilizados, critério de parada e representação do cromossomo.
    - **Elemento visual:** Figura 2 - Fluxograma do algoritmo genético utilizado.

    ### 4. Execução das Simulações
    - Detalha o ambiente de simulação, condições de contorno, número de iterações e critérios de avaliação dos indivíduos.
    - **Elemento visual:** Equação 1 - Cálculo do fitness com base no contraste óptico.

    ### 5. Reprodutibilidade e Limitações
    - Aponta limitações como simulação única, sensibilidade a parâmetros iniciais e ausência de repetição estatística.

    ### 6. Diferenciais da Abordagem Metodológica
    - Destaca o uso do AG como método de projeto automatizado para estruturas ópticas com múltiplas entradas.
  agent: core_chapters_outliner
  context: [generate_outline_results_discussion, generate_outline_conclusion]
