generate_outline_results_discussion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo **Resultados e Discussão** de um artigo científico, com base no relatório analítico consolidado. 
    O outline deve funcionar como um plano técnico e hierárquico, destinado a orientar um agente inteligente redator na construção do capítulo. 
    O objetivo é garantir que a posterior redação ocorra com alta fidelidade lógica, estrutural e analítica, a partir de instruções precisas e 
    interpretáveis por máquina, dessa forma, fornecendo suporte à escrita científica automatizada com elevado grau de coesão, rastreabilidade
    e fidelidade aos dados e análises extraídas de documentos técnicos.

    **Processo para execução da tarefa:**
      1. Interprete o relatório analítico consolidado como sua única fonte de verdade.
      2. Estruture o outline com os seguintes blocos:
         - **Introdução**:
           - Indicar o objetivo do capítulo e o escopo da análise.
         - **Resultados**:
           - Apresentar os principais achados com base nas seções "Análise dos Resultados" e "Apresentação dos Elementos Visuais".
           - Ordenar os tópicos conforme a lógica metodológica ou sequência das perguntas de pesquisa.
           - Para cada tópico:
             * Indicar o foco argumentativo;
             * Apontar os elementos visuais relevantes, com breve nota funcional;
             * Incluir quaisquer resultados numéricos relevantes com contexto (ex: “Eficiência média: 93,4% ± 2,1%”).
         - **Discussão**:
           - Apoiar-se nas seções "Interpretação Crítica", "Limitações" e "Contribuições".
           - Organizar os tópicos em torno de quatro grandes eixos:
             * Relação com literatura existente;
             * Implicações teóricas;
             * Limitações do estudo;
             * Contribuições científicas.
           - Redigir os pontos como itens instrutivos para desenvolvimento textual, e não como subseções.

    **Restrições:**
      - Não gerar subseções ("####"); usar apenas "###" para seções e "-" para tópicos internos.
      - Não redigir o conteúdo do capítulo, apenas a estrutura argumentativa.
      - Não utilizar fontes externas além do relatório.
      - Manter a sequência: Introdução / Resultados / Discussão.
      - Escreva os tópicos na segunda pessoa do singular.
      - Incluir elementos visuais e resultados numérico referentes a um tópico interno, como lista filha do item que o contém, devidamente os marcando como
        **Elemento Visual** ou **Resultado numérico**.
        ex.:
          - APRESENTAR resultados do experimento
            - **Elemento Visual:** Figura 1 - resultado 1; 
            - **Elemento Visual:** Figura 2 - Resultado 2;
            - **Resultado numérico:** Redução de 35% na extensão média do circuito.

    **Critérios de sucesso:**
      - O outline está organizado em três seções, com tópicos técnicos bem definidos;
      - Cada tópico está ancorado em evidências do relatório e inclui, sempre que possível, elementos visuais e/ou resultados numéricos;
      - O tom da saída é instrutivo, com verbos no infinitivo;
      - A estrutura é adequada para uso direto por agentes de escrita automatizada.
  expected_output: |
    Um outline para o capítulo **Resultados e Discussão**, estruturado com três seções principais ("###") e listas de tópicos internos com marcador "-".

    Exemplo de saída:

    ## Resultados e Discussão

    ### Introdução
    - APRESENTAR o propósito do capítulo, que é descrever os principais resultados obtidos nas simulações e analisar suas implicações teóricas e práticas.
    - ANTECIPAR as dimensões que serão exploradas: desempenho computacional, validade da porta lógica, eficiência estrutural.

    ### Resultados
    - APRESENTAR a eficácia do algoritmo genético na convergência dos parâmetros ótimos da porta lógica.
      - **Elemento visual:** Figura 3 - Representa o progresso do fitness.
      - **Resultado numérico:** Convergência alcançada em 84% das execuções em menos de 50 gerações.
    - DESCREVER os testes de validação da funcionalidade da porta OR com cinco entradas.
      - **Elemento visual:** Tabela 1 - Estados de entrada e saída esperados.
      - **Resultado numérico:** Acerto lógico: 100% nos 32 casos simulados.
    - COMPARAR a complexidade estrutural da solução proposta com abordagens tradicionais.
      - **Elemento visual:** Figura 2 - Redução do número de elementos óticos.
      - **Resultado numérico:** Redução de 35% na extensão média do circuito.

    ### Discussão
    - RELACIONAR os achados com trabalhos anteriores, destacando a melhoria de desempenho e simplificação arquitetônica.
    - ANALISAR o impacto do uso de AGs na modelagem de estruturas ópticas escaláveis.
    - IDENTIFICAR as limitações do estudo, como a ausência de verificação experimental em ambiente real.
    - DESTACAR as contribuições para o campo de circuitos fotônicos integrados, com foco em escalabilidade e eficiência.
      - **Elementos visuais:** Figuras 4, 5 e 6.
  agent: core_chapters_outliner

generate_outline_conclusion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo de **Conclusão** de um artigo científico, com base no relatório analítico consolidado
    e no outline previamente gerado para o capítulo de Resultados e Discussão, criado na tarefa anterior, generate_outline_results_discussion.
    O objetivo do outline é fornecer uma estrutura lógica e funcional que será utilizada por um agente inteligente redator para construir o texto 
    final do capítulo. A conclusão deve sintetizar os principais achados do estudo, refletir sobre suas limitações e destacar as contribuições 
    científicas e técnicas da pesquisa. Esse plano textual deve permitir que o redator construa um encerramento forte, coeso e tecnicamente fundamentado.

    **Processo para execução da tarefa:**
      1. Analise o conteúdo do relatório analítico consolidado, com ênfase nas seções "Interpretação Crítica", "Avaliação das Limitações" e "Contribuições".
      2. Examine o outline de Resultados e Discussão para garantir continuidade lógica com os achados apresentados.
      3. Estruture o outline com os seguintes blocos (usando "###" para seções):
         - **Síntese dos Resultados**: 
           - SINTETIZAR os principais achados discutidos no capítulo anterior;
           - RETOMAR valores numéricos ou tendências relevantes que sustentam a conclusão.
         - **Limitações do Estudo**:
           - RECONHECER eventuais restrições metodológicas ou escopos parciais;
           - INDICAR consequências práticas dessas limitações na aplicabilidade dos resultados.
         - **Contribuições Científicas e Técnicas**:
           - DESTACAR os méritos da abordagem proposta, tanto conceituais quanto metodológicos;
           - RELACIONAR as contribuições ao estado da arte da área.
         - **Perspectivas Futuras** (opcional):
           - SUGERIR caminhos viáveis para continuidade do trabalho, com base nas descobertas e limitações registradas.

    **Restrições:**
      - O outline não deve conter texto redacional completo;
      - Não devem ser introduzidas novas interpretações ou extrapolações;
      - Deve-se evitar subtópicos artificiais: a estrutura deve usar apenas seções ("###") e tópicos descritivos em lista ("-").

    **Critérios de sucesso:**
      - O outline apresenta tópicos claros e objetivos para cada bloco da conclusão;
      - Os pontos estão diretamente ancorados no relatório;
      - A sequência favorece o fechamento lógico do artigo, com fluidez em relação ao capítulo anterior;
      - O tom é instrutivo e adequado para consumo por agentes autônomos de escrita.
  expected_output: |
    Um outline estruturado para o capítulo **Conclusão**, com seções organizadas por "###" e tópicos internos listados com marcador "-".
    Os verbos devem ser escritos no infinitivo, orientando o comportamento de um agente redator.

    Exemplo de saída:

    ## Conclusão

    ### Síntese dos Resultados
    - REAFIRMAR o sucesso da modelagem da porta OR multientrada via algoritmos genéticos.
    - SINTETIZAR os principais achados: eficiência de 94,7%, redução estrutural de 35%, acurácia de 100% nos testes simulados.
    - RELACIONAR os achados às perguntas de pesquisa estabelecidas na introdução.

    ### Limitações do Estudo
    - IDENTIFICAR a ausência de validação experimental como um fator que restringe a aplicabilidade direta dos resultados.
    - APONTAR a dependência de parâmetros do algoritmo genético como possível fonte de variação nos resultados.
    - INDICAR a necessidade de replicabilidade para reforçar robustez da proposta.

    ### Contribuições Científicas e Técnicas
    - DESTACAR a redução de elementos ópticos como contribuição prática para a miniaturização de circuitos.
    - RESSALTAR o uso inovador de AGs no contexto de lógica óptica multientrada.
    - EVIDENCIAR o potencial do método para outras aplicações fotônicas.

    ### Perspectivas Futuras
    - SUGERIR o desenvolvimento de portas AND, XOR ou estruturas lógicas combinadas com controle programável.
    - PROPOR a integração da abordagem em sistemas fotônicos maiores e escaláveis.
  agent: core_chapters_outliner
  context: [generate_outline_results_discussion]

generate_outline_methodology:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo de **Metodologia** de um artigo científico, com base no relatório analítico consolidado (report), 
    e nos outlines previamente gerados para os capítulos de Resultados e Discussão e Conclusão, gerados nas tarefas anteriores, 
    generate_outline_results_discussion e generate_outline_conclusion, respectivamente.
    O objetivo da tarefa é construir um plano técnico, objetivo e hierárquico, que permita a um agente inteligente redator compor o capítulo de 
    Metodologia, descrevendo exclusivamente os procedimentos, técnicas e critérios empregados no desenvolvimento do estudo, sem incluir dados, 
    interpretações ou resultados.

    **Processo para execução da tarefa:**
      1. Examine os outlines dos capítulos de Resultados e Conclusão para garantir consistência entre a metodologia e os dados posteriormente obtidos.
      2. Utilize a seção **Apresentação dos Elementos Visuais** para identificar fluxogramas, diagramas, equações ou pseudocódigos relacionados ao processo metodológico.
      3. Use a seção **Análise dos Resultados** apenas como fonte para inferir o que foi feito (jamais para citar resultados).
      4. Recorra às seções **Interpretação Crítica** e **Limitações** apenas para identificar fragilidades do método, sem discuti-las.
      5. Estruture o capítulo em blocos metodológicos (com o operador "###") que sigam a lógica do processo técnico, da definição do problema até a avaliação do modelo.
         Para cada seção, liste tópicos internos como instruções com marcador "-" no infinitivo.

    **Restrições:**
      - Não incluir análises de dados, valores obtidos, gráficos de resultados ou interpretações.
      - É proibido transformar tópicos em subtópicos hierárquicos com "####".
      - O foco é exclusivo no “como foi feito”, “com que critérios” e “por que esses métodos foram adotados”.

    **Critérios de sucesso:**
      - O outline descreve com clareza todas as etapas técnicas do processo, com instruções de escrita bem definidas;
      - Elementos visuais incluídos possuem função exclusivamente técnica;
      - O encadeamento metodológico segue a ordem: definição do problema → parametrização → implementação → simulação → avaliação → limitações;
      - A estrutura final está pronta para ser consumida por um agente redator técnico com mínima ambiguidade.
  expected_output: |
    Um outline estruturado para o capítulo **Metodologia**, composto por seções "###" correspondentes a cada etapa do processo técnico.
    Cada seção conterá tópicos internos listados com marcador "-", redigidos no infinitivo, descrevendo com clareza o que o redator deverá abordar.
    Elementos visuais devem ser incluídos sempre que contribuírem para a compreensão técnica do método.

    Exemplo de saída:

    ## Metodologia

    ### Definição do Problema e Objetivos Técnicos
    - DEFINIR o objetivo de projetar uma porta lógica OR multientrada.
    - EXPLICAR a motivação para otimizar a complexidade estrutural do circuito fotônico.

    ### Parametrização do Espaço de Soluções
    - DESCREVER os parâmetros do modelo (ex: espaçamento, largura, ângulo de entrada).
    - JUSTIFICAR as faixas de variação dos parâmetros com base na viabilidade física.
    - **Elemento visual:** Tabela 1 - Lista dos parâmetros manipulados pelo algoritmo.

    ### Implementação do Algoritmo Genético
    - EXPLICAR a estrutura do algoritmo (codificação, seleção, cruzamento, mutação).
    - DEFINIR a função de fitness e os critérios de parada.
    - **Elemento visual:** Figura 2 - Fluxograma do processo de otimização.

    ### Ambiente de Simulação
    - INFORMAR o simulador utilizado e os recursos computacionais empregados.
    - DETALHAR o número de execuções e as condições de contorno aplicadas.

    ### Critérios de Avaliação
    - ESPECIFICAR os critérios de avaliação adotados (ex: contraste mínimo, número de elementos).
    - EVITAR mencionar valores obtidos — apenas as regras de decisão utilizadas.

    ### Limitações da Abordagem
    - IDENTIFICAR eventuais fragilidades metodológicas como ausência de validação experimental.
    - APONTAR restrições do modelo quanto à generalização ou repetibilidade.
  agent: core_chapters_outliner
  context: [generate_outline_results_discussion, generate_outline_conclusion]
