generate_outline_results_discussion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para a seção de **Resultados e Discussão** de um artigo científico, com base no relatório analítico consolidado. 
    O outline deve servir como um **plano técnico e hierárquico**, projetado para orientar um agente redator na produção da seção com alta fidelidade lógica, 
    estrutural e argumentativa.

    **Processo para execução da tarefa:**
      1. Use exclusivamente o relatório como base — não consulte fontes externas.
      2. Estruture o outline com os com uma única seção de nível 1, com o título principal da seção "Resultados e Discussão", contendo a introdução a ela.
      Escreva os tópicos a serem abordados na introdução da seção.
      3. Estruture a primeira subseção de nível 2, com título "Resultados". Essa subseção deverá abordar todos os resultados obtidos no estudo.
      4. Estruture a segunda subseção de nível 2, com título "Discussões". Essa subseção deverá discutir todos os resultados obtidos no estudo.S
      5. Os tópicos devem ser escritos como instruções textuais em tom imperativo (ex: DESCREVER, ANALISAR, ILUSTRAR...).
      5. Quando pertinente, adicione resultados numéricos como **subitens de um tópico**, com descrição clara e contextualizada do valor.

    **Restrições:**
      - Não redija nenhum conteúdo do capítulo, apenas o outline conforme modelo.
      - Os tópicos devem estar no **imperativo** e redigidos na segunda pessoa do singular (ex: “DESCREVER os resultados obtidos...”).

    **Critérios de sucesso:**
      - A saída possui uma seção principal: "Resultados e Discussão"; e duas subseções: "Resultados" e "Discussão"
      - Cada seção contém um bloco de tópicos a serem abordados no seu respectivo texto.
      - Os tópicos estão bem definidos, específicos, e diretamente ancorados no relatório.
      - A saída está pronta para uso direto por um agente escritor automatizado.
  expected_output: |
    Um outline para a seção **Resultados e Discussão** de um artigo ciêntífico, com uma seção e duas subseções, 
    cada uma contendo um bloco de "Tópicos a abordar no texto:" e, quando necessário, subitens de resultados numéricos.

    Exemplo:

    ## Resultados e Discussão
    - APRESENTAR o propósito do capítulo: relatar os resultados obtidos com a modelagem da porta lógica OR de cinco entradas utilizando algoritmos genéticos e discutir suas implicações. 
    - ANTECIPAR os aspectos que serão explorados: eficiência do algoritmo, desempenho óptico da porta OR, robustez estrutural e limitações identificadas. 

    ### Resultados
    - DESCREVER a eficiência do algoritmo genético na convergência das soluções ao longo das gerações.
      Elementos visuais a contextualizar:
      - **Elemento visual:** Figura 13 - Evolução do fitness para a primeira porta.
      - **Elemento visual:** Figura 15 - Evolução do fitness para a segunda porta.
      Resultados a incluir:
      - **Resultado numérico:** Saturação observada por volta da 30ª e 50ª gerações.
    - ANALISAR os resultados das tabelas verdade para validar a funcionalidade lógica da porta OR com cinco entradas.
      Elementos visuais a contextualizar:
      - **Elemento visual:** Tabela 1 - Contrastes da primeira porta.
      - **Elemento visual:** Tabela 2 - Contrastes da segunda porta.
      Resultados a incluir:
      - **Resultado numérico:** CR(Out) > 0,30 em 100% dos casos simulados.

    ### Discussão
    - RELACIONAR os resultados obtidos com a literatura anterior, destacando a viabilidade da solução proposta e sugerindo necessidade de comparação quantitativa.
    - ANALISAR as implicações teóricas do uso de algoritmos genéticos na modelagem de circuitos ópticos multientrada.
    - IDENTIFICAR as principais limitações da pesquisa, como:
      - Ausência de validação experimental;
      - Violação parcial de critérios geométricos;
      - Ausência de análise estatística entre múltiplas execuções.
    - DESTACAR as contribuições do estudo, incluindo:
      - Preenchimento de lacuna na literatura sobre portas OR quíntuplas em fibra óptica;
      - Redução da complexidade estrutural em circuitos lógicos ópticos;
      - Proposta replicável com base em código-fonte claro e condições bem definidas.
      Elementos visuais a contextualizar:
      - **Elementos visuais:** Figuras 13, 15, 16; Código-fonte 12.
  agent: core_chapters_outliner

generate_outline_conclusion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo de **Conclusão** de um artigo científico, com base no relatório analítico consolidado
    e no outline previamente gerado para o capítulo de Resultados e Discussão, criado na tarefa anterior, generate_outline_results_discussion.
    O objetivo do outline é fornecer uma estrutura lógica e funcional que será utilizada por um agente inteligente redator para construir o texto 
    final do capítulo. A conclusão deve sintetizar os principais achados do estudo, refletir sobre suas limitações e destacar as contribuições 
    científicas e técnicas da pesquisa. Esse plano textual deve permitir que o redator construa um encerramento forte, coeso e tecnicamente fundamentado.

    **Processo para execução da tarefa:**
      1. Analise o conteúdo do relatório analítico consolidado, com ênfase nas seções "Interpretação Crítica", "Avaliação das Limitações" e "Contribuições".
      2. Examine o outline de Resultados e Discussão para garantir continuidade lógica com os achados apresentados.
      3. Estruture o outline com os seguintes blocos (usando "###" para seções):
         - **Síntese dos Resultados**: 
           - SINTETIZAR os principais achados discutidos no capítulo anterior;
           - RETOMAR valores numéricos ou tendências relevantes que sustentam a conclusão.
         - **Limitações do Estudo**:
           - RECONHECER eventuais restrições metodológicas ou escopos parciais;
           - INDICAR consequências práticas dessas limitações na aplicabilidade dos resultados.
         - **Contribuições Científicas e Técnicas**:
           - DESTACAR os méritos da abordagem proposta, tanto conceituais quanto metodológicos;
           - RELACIONAR as contribuições ao estado da arte da área.
         - **Perspectivas Futuras** (opcional):
           - SUGERIR caminhos viáveis para continuidade do trabalho, com base nas descobertas e limitações registradas.

    **Restrições:**
      - O outline não deve conter texto redacional completo;
      - Não devem ser introduzidas novas interpretações ou extrapolações;
      - Deve-se evitar subtópicos artificiais: a estrutura deve usar apenas seções ("###") e tópicos descritivos em lista ("-").

    **Critérios de sucesso:**
      - O outline apresenta tópicos claros e objetivos para cada bloco da conclusão;
      - Os pontos estão diretamente ancorados no relatório;
      - A sequência favorece o fechamento lógico do artigo, com fluidez em relação ao capítulo anterior;
      - O tom é instrutivo e adequado para consumo por agentes autônomos de escrita.
  expected_output: |
    Um outline estruturado para o capítulo **Conclusão**, com seções organizadas por "###" e tópicos internos listados com marcador "-".
    Os verbos devem ser escritos no infinitivo, orientando o comportamento de um agente redator.

    Exemplo de saída:

    ## Conclusão

    ### Síntese dos Resultados
    - REAFIRMAR o sucesso da modelagem da porta OR multientrada via algoritmos genéticos.
    - SINTETIZAR os principais achados: eficiência de 94,7%, redução estrutural de 35%, acurácia de 100% nos testes simulados.
    - RELACIONAR os achados às perguntas de pesquisa estabelecidas na introdução.

    ### Limitações do Estudo
    - IDENTIFICAR a ausência de validação experimental como um fator que restringe a aplicabilidade direta dos resultados.
    - APONTAR a dependência de parâmetros do algoritmo genético como possível fonte de variação nos resultados.
    - INDICAR a necessidade de replicabilidade para reforçar robustez da proposta.

    ### Contribuições Científicas e Técnicas
    - DESTACAR a redução de elementos ópticos como contribuição prática para a miniaturização de circuitos.
    - RESSALTAR o uso inovador de AGs no contexto de lógica óptica multientrada.
    - EVIDENCIAR o potencial do método para outras aplicações fotônicas.

    ### Perspectivas Futuras
    - SUGERIR o desenvolvimento de portas AND, XOR ou estruturas lógicas combinadas com controle programável.
    - PROPOR a integração da abordagem em sistemas fotônicos maiores e escaláveis.
  agent: core_chapters_outliner
  context: [generate_outline_results_discussion]

generate_outline_methodology:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo de **Metodologia** de um artigo científico, com base no relatório analítico consolidado (report), 
    e nos outlines previamente gerados para os capítulos de Resultados e Discussão e Conclusão, gerados nas tarefas anteriores, 
    generate_outline_results_discussion e generate_outline_conclusion, respectivamente.
    O objetivo da tarefa é construir um plano técnico, objetivo e hierárquico, que permita a um agente inteligente redator compor o capítulo de 
    Metodologia, descrevendo exclusivamente os procedimentos, técnicas e critérios empregados no desenvolvimento do estudo, sem incluir dados, 
    interpretações ou resultados.

    **Processo para execução da tarefa:**
      1. Examine os outlines dos capítulos de Resultados e Conclusão para garantir consistência entre a metodologia e os dados posteriormente obtidos.
      2. Utilize a seção **Apresentação dos Elementos Visuais** para identificar fluxogramas, diagramas, equações ou pseudocódigos relacionados ao processo metodológico.
      3. Use a seção **Análise dos Resultados** apenas como fonte para inferir o que foi feito (jamais para citar resultados).
      4. Recorra às seções **Interpretação Crítica** e **Limitações** apenas para identificar fragilidades do método, sem discuti-las.
      5. Estruture o capítulo em blocos metodológicos (com o operador "###") que sigam a lógica do processo técnico, da definição do problema até a avaliação do modelo.
         Para cada seção, liste tópicos internos como instruções com marcador "-" no infinitivo.

    **Restrições:**
      - Não incluir análises de dados, valores obtidos, gráficos de resultados ou interpretações.
      - É proibido transformar tópicos em subtópicos hierárquicos com "####".
      - O foco é exclusivo no “como foi feito”, “com que critérios” e “por que esses métodos foram adotados”.

    **Critérios de sucesso:**
      - O outline descreve com clareza todas as etapas técnicas do processo, com instruções de escrita bem definidas;
      - Elementos visuais incluídos possuem função exclusivamente técnica;
      - O encadeamento metodológico segue a ordem: definição do problema → parametrização → implementação → simulação → avaliação → limitações;
      - A estrutura final está pronta para ser consumida por um agente redator técnico com mínima ambiguidade.
  expected_output: |
    Um outline estruturado para o capítulo **Metodologia**, composto por seções "###" correspondentes a cada etapa do processo técnico.
    Cada seção conterá tópicos internos listados com marcador "-", redigidos no infinitivo, descrevendo com clareza o que o redator deverá abordar.
    Elementos visuais devem ser incluídos sempre que contribuírem para a compreensão técnica do método.

    Exemplo de saída:

    ## Metodologia

    ### Definição do Problema e Objetivos Técnicos
    - DEFINIR o objetivo de projetar uma porta lógica OR multientrada.
    - EXPLICAR a motivação para otimizar a complexidade estrutural do circuito fotônico.

    ### Parametrização do Espaço de Soluções
    - DESCREVER os parâmetros do modelo (ex: espaçamento, largura, ângulo de entrada).
    - JUSTIFICAR as faixas de variação dos parâmetros com base na viabilidade física.
    - **Elemento visual:** Tabela 1 - Lista dos parâmetros manipulados pelo algoritmo.

    ### Implementação do Algoritmo Genético
    - EXPLICAR a estrutura do algoritmo (codificação, seleção, cruzamento, mutação).
    - DEFINIR a função de fitness e os critérios de parada.
    - **Elemento visual:** Figura 2 - Fluxograma do processo de otimização.

    ### Ambiente de Simulação
    - INFORMAR o simulador utilizado e os recursos computacionais empregados.
    - DETALHAR o número de execuções e as condições de contorno aplicadas.

    ### Critérios de Avaliação
    - ESPECIFICAR os critérios de avaliação adotados (ex: contraste mínimo, número de elementos).
    - EVITAR mencionar valores obtidos — apenas as regras de decisão utilizadas.

    ### Limitações da Abordagem
    - IDENTIFICAR eventuais fragilidades metodológicas como ausência de validação experimental.
    - APONTAR restrições do modelo quanto à generalização ou repetibilidade.
  agent: core_chapters_outliner
  context: [generate_outline_results_discussion, generate_outline_conclusion]
