analyze_report_for_results:
  description: >
    **Analytical Report**  
    {report}  

    Analyze the provided analytical report to extract key information necessary for generating a structured outline for the "Results" subsection 
    of a scientific paper. Focus on identifying the research focus, primary findings, relevant statistics, and supporting visuals that align with the 
    study's objectives.  

    **Input Detaling**:  
    - **Analytical Report**
      - Has the following five sections:  
        1. Apresentação Clara dos Elementos Visuais (Presentation of Visual Elements)  
        2. Análise dos Resultados (Analysis of Results)  
        3. Interpretação Crítica (Critical Interpretation)  
        4. Avaliação das Limitações do Estudo (Evaluation of Study Limitations)  
        5. Contribuições (Contributions)  

    **Execution Steps**:  
    1. Review the **Analytical Report**, focusing primarily on sections 1, 2, and with section 5 for context to identify:  
        - **Research Focus/Scope**: The study's primary objective or question, inferred from section 2's results and section 5's contributions.  
        - **Findings**: The research's key results (quantitative or qualitative) addressing the research focus, from section 2, with 
          Statistics/Metrics.  
        - **Visuals**: Relevant visual elements that help support findings and/or statistics/metrics (e.g., graphs, tables) from section 1.  
    2. Organize findings thematically (e.g., by measured variable) or chronologically (e.g., by experimental phase) based on section 2's structure.  
    3. Summarize the extracted information in a structured text format, including:  
        - **Research Focus/Scope**: A clear statement of the study's objective or question.  
        - **Findings**: The key findings with associated statistics/metrics.  
        - **Visuals**: Visuals elements that support the findings with metadata and short descriptions, explicitly identifying to which finding 
          they tie to.  

    **Guidelines**:  
    - **Research Focus/Scope**: Explicitly state the study's objective or question, using section 2 and 5 to infer the researcher's intent.  
    - **Findings**: Identify the results (positive or negative) tied to the research focus, from section 2, with Statistics/Metrics (processed results, 
      e.g., “Accuracy of 95%”, “p < 0.01”).  
    - **Visuals**: Select 0-2 relevant visuals per fiding from section 1, with complete metadata (title, source, legend) that help support the findings, 
      be it helping on the fiding's context or present it's results. 
    - **Organization**: Use the report's internal structure (e.g., section 2's result sequence) for ordering findings, not an external Methods section.  

    **Restrictions**:  
    - Focus only on sections 1 and 2 for findings and visuals; use section 5 for research focus context; exclude sections 3 and 4 to avoid 
      interpretation or limitations.  
    - Do not invent data or modify report content.  

    **Success Criteria**:  
    - Produces a clear, structured text summary of the research focus, findings, visuals, and associated statistics.  
    - Aligns with the study's objectives as inferred from the report, without relying on external sections.   
    - Suitable as direct input for structuring the Results subsection's outline.  

  expected_output: >
    A structured text summary, formatted in markdown, containing the research focus/scope, findings and visuals that help explain them, following the 
    structure:  
    **Results Analysis Summary**:  
    - **Research Focus/Scope**: A clear statement of the study's primary objective or question (e.g., “To evaluate the performance of a five-input OR 
      optical logic gate”).  
    - **Findings**:  
      - Finding 1: Description, statistic (e.g., “Achieved 95% accuracy, p < 0.01”).  
      - Finding 2: Description, statistic.  
      - ...  
    - **Visuals**:  
      - Visual 1: Title, source, legend, short description.  
      - Visual 2: Title, source, legend, short description.  

  agent: report_analyst

structure_results_outline:
  description: >
    Convert the structured analysis summary into a complete and coherent outline for the "Results" subsection of a scientific paper. This task combines the
    extraction of key discussion topics with the construction of detailed topic entries, including visual elements, numerical results, and narrative 
    guidance, to assist a Writer Agent in producing an objective, well-structured narrative.

    **Input**:
    - Structured analysis summary (markdown "Results Analysis Summary") from `analyze_report_for_results`, containing:
      - **Research Focus/Scope**: A clear statement of the study's primary objective or question.
      - **Findings**: A list of key findings, each with a description and associated statistic.
      - **Visuals**: A list of visual elements, each with title, source, legend, and short description.

    **Execution Steps**:
    1. Review the summary to identify the research scope, key findings, and supporting data.
    2. Organize the findings to serve as discussion topics. Organize them thematically or chronologically, ensuring alignment with the research scope.
    3. For each discussion topic:
       - Create a concise, descriptive title (e.g., "Throughput Performance of Optical Gate").
       - Set the rhetorical purpose to "Present findings".
       - Write a topic description summarizing the key finding in context.
       - Include 0-1 relevant visual elements, each with metadata: `identifier`, `name`, `role_in_topic`.
       - Include 0-1 relevant `numerical_results`, each with metadata: `verbatim_value`, `context_description`, `associated_visual`.
       - Write a narrative guidance with clear, actionable instructions (e.g., "Start by presenting X, then describe Y using Figure 1").
    4. After all topics are created, define the subsection's flow, listing the topic titles in logical order, separated by " -> ".

    **Guidelines**:
    - Maintain an objective and descriptive tone.
    - Use past-tense verbs for findings (e.g., "Found", "Measured").
    - Do not include interpretations or implications—focus strictly on what was observed.
    - Ensure each topic is distinct and clearly linked to the research scope.
    - Base content solely on the summary; do not introduce external assumptions or data.

    **Restrictions**:
    - Do not alter topic titles or their rhetorical purpose once created.
    - Do not infer meaning beyond the provided summary.

    **Success Criteria**:
    - Produces a full outline with clearly defined topics under the "Results" subsection.
    - Each topic includes visuals (if any are relevant), numerical results, and narrative guidance.
    - The subsection's flow reflects a logical and coherent progression.

  expected_output: >
    A structured outline for the "Results" subsection to guide the Writer Agent in producing a detailed, objective narrative. The output must include:
    - `subsection_name`: Set to "Results"
    - `subsection_flow`: A string listing the ordered `topic` titles, separated by " -> "
    - `discussion_topics`: A list of 3-5 items, each containing:
      - `topic`: Concise title of the finding
      - `rhetorical_purpose`: Always "Present findings"
      - `topic_description`: Brief summary of the finding and its context
      - `visual_elements`: Up to one element with metadata
      - `numerical_results`: Up to one result with metadata
      - `narrative_guidance`: Clear instructions to guide the Writer Agent

  agent: results_outliner
  context: [analyze_report_for_results]

analyze_report_for_discussion:
  description: >
    **Analytical Report**  
    {report}  

    Extract interpretive content, implications, limitations, and visuals from the provided analytical report that are tied to the topics of the "Results" 
    subsection outline to support generating a structured outline for the "Discussion" subsection of a scientific paper. Focus on sections 3 (Critical 
    Interpretation), 4 (Evaluation of Study Limitations), and 5 (Contributions) of the report, and use the Results outline to ground interpretations  
    and produce a concise, structured text summary.

    **Inputs**:  
    - Analytical report with the following five sections:  
      1. Apresentação Clara dos Elementos Visuais (Presentation of Visual Elements)  
      2. Análise dos Resultados (Analysis of Results)  
      3. Interpretação Crítica (Critical Interpretation)  
      4. Avaliação das Limitações do Estudo (Evaluation of Study Limitations)
      5. Contribuições (Contributions)
    - Structured outline from `structure_results_outline` (JSON format), containing:
      - `subsection_name`: (e.g., "Results")
      - `subsection_flow`: (e.g., "Topic A -> Topic B")
      - `discussion_topics`: A list, where each topic includes `topic` title, `rhetorical_purpose`, `topic_description`, `visual_elements`, `numerical_results`, and `narrative_guidance`.

    **Execution Steps**:  
    1. Review sections 3, 4, and 5 of the **Analytical Report** to identify:  
      - Literature comparisons or gaps (section 3, e.g., comparisons to prior studies).  
      - Implications (section 5, e.g., practical or theoretical impacts).  
      - Limitations (section 4, e.g., methodological constraints).  
      - Future research directions (sections 4 and 5, e.g., next steps).  
    2. Review the "Results" subsection structured outline from `structure_results_outline` to extract:
      - Topics of discussed for continuity.
      - Key findings to ground interpretations.  
      - Visuals for potential reuse.  
    4. Write a structured text summary with:  
      - **Research Question and Findings**: Restate the research question and key findings from the Results outline.  
      - **Literature Connections**: Comparisons or gaps from section 3.  
      - **Implications**: Key impacts from section 5.  
      - **Limitations**: Constraints from section 4.  
      - **Future Directions**: Proposed next steps from sections 4 and 5.  
      - **Visuals**: 1-2 visuals (reused from Results or new from section 1), with identifier and name.  

    **Guidelines**:  
    - **Literature Connections**: Extract 1-2 specific comparisons or gaps (e.g., "Study X found Y, but our results show Z").  
    - **Implications**: Focus on practical or theoretical impacts from section 5.  
    - **Limitations**: List methodological or scope constraints from section 4.  
    - **Future Directions**: Propose research based on sections 4 and 5.  
    - **Visuals**: Prioritize Results outline visuals; add from section 1 if needed, with full metadata.  

    **Restrictions**:  
    - Use only sections 3, 4, 5 for interpretive content and section 1 for new visuals; ignore section 2.  
    - Do not modify findings from the "Results" subsection structured outline from `generate_results_outline`.  
    - Do not invent data or add external information.

    **Success Criteria**:  
    - Delivers a structured text summary with literature connections, implications, limitations, future directions, and 1-2 visuals.  
    - Grounds content in Results outline findings and report sections 3, 4, 5.  
    - Suitable for generation of a structured outline for the "Discussion" subsection.  

  expected_output: >
    A structured text summary, formatted as:  
    **Discussion Analysis Summary**:  
    - **Research Question and Findings**: Restatement of research question and key findings from Results outline.  
    - **Literature Connections**:  
      - Connection 1: Description (e.g., comparison to prior study).  
      - Connection 2: Description.  
    - **Implications**: Description of impacts.  
    - **Limitations**: Description of constraints.  
    - **Future Directions**: Proposed next steps.  
    - **Visuals**:  
      - Visual 1: Title, source, legend, description.  
      - Visual 2: Title, source, legend, description.  

  agent: report_analyst
  context: [structure_results_outline]

structure_discussion_outline:
  description: >
    Convert the structured discussion analysis summary into a full outline for the "Discussion" subsection of a scientific paper.
    This task extracts interpretive topics (3-5) from the summary and then enriches each topic with visuals, numerical results,
    narrative guidance and a logical flow, guiding a Writer Agent to produce an analytical narrative linking findings to
    literature, implications, limitations and future directions.

    input:
      - Structured text summary from `analyze_report_for_discussion`, containing:
        - research questions and findings
        - literature_connections (1-2 items)
        - implications
        - limitations
        - future_directions
        - visuals (1-2 items with metadata)

    execution_steps:
      1. Parse the summary to identify interpretive elements: research question, key findings, literature comparisons, implications,
        limitations and future directions.
      2. Select 3-5 distinct discussion topics based on those elements, ensuring:
        - first topic addresses research question + findings
        - last topic covers future directions
        - all are distinct and cover literature, implications or limitations.
      3. For each topic:
        - Create `topic`: concise title (e.g., "Comparison with Previous Studies").
        - Define `rhetorical_purpose` (e.g., "Compare findings", "Discuss implications").
        - Write `topic_description`: summary of focus and key points.
        - Include up to 1 `visual_element` from summary with metadata:
          `identifier`, `name`, `description`, `source`, `role_in_topic`.
        - Include up to 1 `numerical_result` with metadata:
          `verbatim_value`, `context_description`, `associated_visual`.
        - Write `narrative_guidance`: clear, actionable instruction
          (e.g., "Start by restating finding, then compare to Smith et al. using Figure 1").
      4. Build `subsection_flow`: string with topic titles in order, separated by " -> ".

    guidelines:
      - Use present tense for interpretive verbs, past tense for results.
      - Focus strictly on summary content; do not add external data.
      - Maintain an analytical, objective tone.
      - Limit to 3-5 topics for conciseness.

    restrictions:
      - Do not modify extracted topic titles or rhetorical purposes.
      - Do not assume a Methods section or invent new data.
      - Do not include long narrative; guidance only.

    success_criteria:
      - Returns a JSON with:
        - `subsection_name`: "Discussion"
        - `subsection_flow`: ordered string of topic titles
        - `discussion_topics`: list of 3-5 items, each with:
          - `topic`
          - `rhetorical_purpose`
          - `topic_description`
          - `visual_elements`
          - `numerical_results`
          - `narrative_guidance`

  expected_output: >
    ```json
    {
      "subsection_name": "Discussion",
      "subsection_flow": "Topic1 -> Topic2 -> Topic3",
      "discussion_topics": [
        {
          "topic": "Topic1",
          "rhetorical_purpose": "Compare findings",
          "topic_description": "...",
          "visual_elements": [ /* up to 1 item */ ],
          "numerical_results": [ /* up to 1 item */ ],
          "narrative_guidance": "Start by restating..."
        },
        ...
      ]
    }
    ```

  agent: discussion_outliner
  context: [analyze_report_for_discussion]