generate_outline_results_discussion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para o capítulo de **Resultados e Discussão** de um artigo científico, com base no relatório analítico consolidado. 
    O outline deve funcionar como um plano técnico e hierárquico, destinado a orientar um agente inteligente redator na construção do capítulo. 
    O objetivo é garantir que a posterior redação ocorra com alta fidelidade lógica, estrutural e analítica, a partir de instruções precisas e 
    interpretáveis por máquina, dessa forma, fornecendo suporte à escrita científica automatizada com elevado grau de coesão, rastreabilidade
    e fidelidade aos dados e análises extraídas de documentos técnicos.

    **Processo para execução da tarefa:**
      * Interprete o relatório analítico consolidado como sua única fonte de verdade;
      * Estruture o outline em três blocos principais:
        1. **Introdução**: contextualização do capítulo e dos resultados que serão apresentados.
        2. **Resultados**: organização dos principais achados conforme a sequência metodológica ou lógica das perguntas de pesquisa. Para cada tópico:
            - Defina um título representativo;
            - Descreva o foco argumentativo;
            - Relacione-o com os dados da seção "Análise dos Resultados";
            - Indique os elementos visuais relacionados, com uma breve nota funcional (ex: *"Figura 3: Evidencia a melhoria do contraste óptico após 
              otimização."*).
        3. **Discussão**: tópicos interpretativos baseados nas seções "Interpretação Crítica", "Limitações" e "Contribuições". Inclua subtópicos com 
           os seguintes focos:
            - Relação com a literatura existente;
            - Implicações teóricas;
            - Limitações do estudo;
            - Contribuições científicas.

    **Restrições:**
      * Não redigir o texto do capítulo, apenas sua estrutura com instruções descritivas e funcionais;
      * Não utilizar fontes externas ao relatório;
      * Não modificar a estrutura base (Introdução / Resultados / Discussão);

    **Diretrizes para geração bem sucedida:**
      * O outline segue integralmente a estrutura especificada;
      * Todos os tópicos estão diretamente ancorados em seções do relatório;
      * Os elementos visuais estão contextualizados com função comunicativa clara;
      * A saída está pronta para ser consumida por outro agente inteligente sem necessidade de reinterpretação manual.
  expected_output: |
    Um outline para o capítulo de **Resultados e Discussão** de um artigo científico, ancorado no relatório analítico consolidado, 
    composto por um texto em três níveis hierárquicos: Títulos principais (seções); Tópicos e subtópicos (subseções) com: Título conciso; 
    Descrição funcional orientando o foco da escrita; Indicação dos elementos visuais relevantes e sua função.

    Exemplo de saída:
     ## Resultados e Discussão

    ### Introdução
    - Apresenta o propósito do capítulo e o escopo dos dados que serão analisados.

    ### Resultados

    #### 1. Desempenho do Algoritmo Genético
    - Apresenta os padrões de convergência e estabilidade obtidos nas simulações.
    - **Elemento visual:** Figura 4 - Representa o progresso do fitness ao longo das gerações.

    #### 2. Validação da Porta OR
    - Demonstra o comportamento esperado da lógica OR nas cinco entradas, validado por Tabela 2.
    - **Elemento visual:** Tabela 2 - Mostra os estados de entrada e saída conforme esperado.

    ### Discussão

    #### 1. Relação com Trabalhos Anteriores
    - Compara os resultados obtidos com soluções propostas na literatura.

    #### 2. Implicações Teóricas
    - Analisa o impacto do uso de AGs na modelagem fotônica.

    #### 3. Limitações do Estudo
    - Aponta ausência de repetição de simulações e validação experimental.

    #### 4. Contribuições
    - Destaca a redução de complexidade e o potencial da metodologia para lógica óptica integrada.
  agent: core_chapters_outliner
