generate_outline_results_discussion:
  description: >
    Com base no relatório analítico consolidado, gere um outline estruturado para o capítulo de **Resultados e Discussão**,
    que refleta a estrutura típica esperada para esse capítulo, composta por três partes principais:
    - Um texto introdutório que contextualize os resultados;
    - Uma subseção dedicada à apresentação ordenada dos principais achados;
    - Uma subseção destinada à análise e discussão crítica desses achados.

    Utilize exclusivamente o conteúdo do relatório para fundamentar o outline. A seção de **Análise dos Resultados** deve estruturar a parte de apresentação dos dados;
    a seção de **Interpretação Crítica** deve fundamentar os blocos argumentativos e analíticos da subseção de Discussão; e os elementos listados na 
    **Apresentação Clara dos Elementos Visuais** devem ser integrados estrategicamente nas partes correspondentes do outline, sem serem transcritos.

    O outline deve apresentar os achados do estudo, articular as evidências e interpretações de forma progressiva 
    e lógica, e indicar onde e quais elementos visuais (como tabelas, figuras, equações e/ou trechos de código) devem ser 
    incorporados para apoiar a argumentação.

    Relatório Analítico consolidado:

    {report}

  expected_output: >
    Um outline completo para o capítulo de Resultados e Discussão, contendo:
    - Títulos e subtítulos organizados em ordem lógica;
    - Descrições orientativas de cada seção;
    - Uma seção inicial introdutória com título e descrição;
    - Uma subseção de Resultados com tópicos bem definidos, cada um com título, descrição e indicação de onde os elementos visuais serão utilizados;
    - Uma subseção de Discussão com tópicos interpretativos e analíticos, organizados em sequência lógica e embasados na Interpretação Crítica.

  agent: core_chapters_outliner
