generate_outline_results_discussion:
  description: >
    Relatório analítico consolidado:

    {report}

    Gere um outline estruturado para a seção de **Resultados e Discussão** de um artigo científico, com base no relatório analítico consolidado. 
    O outline deve funcionar como um **plano técnico e hierárquico**, projetado para orientar um agente redator na produção dessa seção com alta 
    fidelidade lógica, estrutural e argumentativa.
    Separate *Results* (factual findings) from *Discussion* (interpretations), incorporate section-specific guidelines, and indicate precise placements 
    for visual elements (tables, figures, graphs).

    **Processo para execução da tarefa:**
      1. Use exclusivamente o relatório como base — não consulte fontes externas.
      2. Estruture o outline com uma única seção de nível 1: "Resultados e Discussão", contendo tópicos introdutórios para contextualizar a seção.
      3. Crie a subseção de nível 2: "Resultados", contendo todos os achados factuais organizados logicamente.
      4. Crie a subseção de nível 2: "Discussão", contendo interpretações críticas dos achados, relações com a literatura, limitações e implicações.
      4. Escreva os tópicos como instruções claras, no **imperativo** e na **segunda pessoa do singular** (ex: "DESCREVER os resultados...").
      5. Quando necessário, adicione **subitens** com resultados numéricos ou elementos visuais, sempre com breve descrição contextual.
      6. Indique explicitamente onde inserir cada elemento visual, com nome e legenda resumida.

    **Restrições:**
      - Não redigir conteúdo do capítulo; apenas o outline conforme especificado.
      - Não sair da estrutura de três blocos: Introdução, Resultados, Discussão.
      - Evite tópicos genéricos ou vagos — todos devem estar ancorados diretamente no conteúdo do relatório.

    **Critérios de sucesso:**
      - O outline contém: uma seção "Resultados e Discussão", com duas subseções: "Resultados" e "Discussão".
      - Cada bloco apresenta tópicos claros, específicos e imperativos, guiando a redação com base nos achados e interpretações.
      - Elementos visuais e resultados numéricos estão corretamente posicionados e contextualizados.
      - A estrutura final é diretamente utilizável por um agente redator automatizado, sem necessidade de ajustes posteriores.

  expected_output: |
    Um outline técnico estruturado para a seção **Resultados e Discussão** de um artigo científico, composto por:
      - Uma seção principal: "Resultados e Discussão"
      - Duas subseções: "Resultados" e "Discussão"
      - Tópicos redigidos no imperativo e na segunda pessoa do singular
      - Subitens contendo resultados numéricos e elementos visuais com legendas resumidas, quando necessário.

    Exemplo:

    ## Resultados e Discussão
    - APRESENTAR o objetivo da seção e conectar com os objetivos gerais da pesquisa.
    - DESTACAR a estrutura que será seguida: apresentação dos achados, seguida de discussão crítica.

    ### Resultados
    - DESCREVER a evolução do fitness ao longo das gerações nos dois experimentos realizados.
      Resultados a incluir:
      - **Resultado numérico:** Saturação observada a partir da geração 30 no primeiro experimento.
      - **Resultado numérico:** Estabilização após a geração 50 no segundo experimento.
      Elementos visuais:
      - **Figura 13:** Evolução do fitness - Experimento 1.
      - **Figura 15:** Evolução do fitness - Experimento 2.
    - ANALISAR os contrastes lógicos obtidos nas tabelas verdade.
      Resultados a incluir:
      - **Resultado numérico:** CR(Out) > 0,30 em 100% dos casos.
      Elementos visuais:
      - **Tabela 1:** Resultados lógicos - Primeira porta.
      - **Tabela 2:** Resultados lógicos - Segunda porta.

    ### Discussão
    - INTERPRETAR os resultados de convergência e sua relação com a eficiência do algoritmo genético.
    - COMPARAR os resultados obtidos com estudos anteriores na área de portas ópticas multientrada.
    - AVALIAR as limitações do estudo, incluindo:
      - Falta de validação experimental.
      - Possível viés geométrico.
      - Ausência de análise estatística interexecuções.
    - APONTAR contribuições relevantes do estudo, como:
      - Inovação no design da porta OR com cinco entradas.
      - Potencial replicação da abordagem proposta.
      Elementos visuais:
      - **Código-fonte 12:** Lógica de modelagem proposta.
  agent: results_discussion_outliner

generate_conclusion_outline:
  description: >
    Analytical report

    {report}

    Generate a structured outline for the Conclusion section of a scientific article, based on the provided analytical report.
    The Conclusion section should reflect upon what was written in the "Results and Discussion" section. You are also provided 
    with the outline of this section, so you can base yours upon.
    This outline will be consumed by another agent responsible for writing the full Conclusion.
    Your outline must guide that agent step by step, ensuring logical flow and rhetorical clarity.

    Execution_steps:
    1. Read and understand the outline of "Results and Discussion";
    2. Read and understand the Analytical report;
    3. Reaffirm the research problem and purpose in a concise opening bullet.
    4. Synthesize the key findings or arguments, grouping related results.
    5. Discuss broader implications, linking findings to the wider field.
    6. Reflect critically on the study's limitations, if not already addressed.
    7. Propose specific, actionable suggestions for future research.
    8. Offer a closing perspective or insight without introducing new data.
    9. End with a strong, cohesive final remark that reinforces the contribution.

    Restrictions:
    - Do not introduce any new information or data.
    - Avoid redundancy—each bullet must cover a unique rhetorical function.
    - Keep each bullet to 1-2 sentences, with clear academic tone.

    Success_criteria:
    - 5 to 7 bullets, each corresponding to one logical paragraph.
    - Each bullet includes a brief description of its content and rhetorical goal.
    - Bullets follow the exact order: Problem → Findings → Implications → Limitations → Future Research → Perspective → Final Remark.
    - Ready for direct consumption by an automated writing agent without further edits.

  expected_output: |
    A list of 5-7 bullets, each 1-2 sentences long, structured as above so that a downstream agent can generate the full Conclusion section 
    in polished academic English.

  agent: conclusion_outliner