results_writing_task:
  description: >
    Rewrite the Results and Discussion section based on the provided draft.
    Ensure clarity, logical structure, and academic rigor while following 
    scientific writing best practices.
    
    Structure the section with clear **subheadings**, present the findings 
    sequentially, and relate them to the research questions or hypotheses.

    Describe key findings **precisely**, referencing **figures, tables, or graphs**, 
    and provide analytical insights for each.

    Compare findings with previous research, highlighting **similarities, 
    differences, and potential explanations** while maintaining a respectful 
    and well-founded tone.

    Address **study limitations**, methodological considerations, and potential 
    improvements for future research.

    Ensure the text is **formal, objective, and academically precise**, avoiding 
    vague expressions and ensuring terminological consistency.

    Here is the draft on which to act up on:
    {draft}

  expected_output: >
    A refined and structured Results and Discussion section that:
    - Clearly presents the findings in a **logical sequence**.
    - Provides precise descriptions of **figures, tables, and graphs**.
    - Includes **comparisons** with previous studies.
    - Discusses **implications** and **limitations**.
    - Uses **formal, objective, and academic language**.
  
  agent: results_writer