methodology_results_consistency:
  description: >
    Analise as chunks {chunk_indexes} do batch {batch_number} do documento {target_document}. 
    Avalie criticamente a relação entre metodologia e resultados, considerando:
    - **Fundamentação e Aplicação dos Métodos:** A justificativa e coerência dos métodos utilizados em relação aos objetivos;
    - **Consistência dos Dados:** A adequação dos resultados em relação à metodologia aplicada;
    - **Coerência das Conclusões:** A validade das inferências feitas a partir dos dados, destacando possíveis inconsistências ou lacunas interpretativas.
    Esse é o conteúdo a ser analisado:
    {content}
  expected_output: >
    Um texto estruturado contendo e objetivo, que apresente:
    1. **Descrição e Avaliação da Metodologia:**
       - Explicação dos métodos aplicados;
       - Verificação da coerência e replicabilidade dos métodos.
    2. **Análise da Relação entre Metodologia e Resultados:**
       - Avaliação da compatibilidade entre os métodos empregados e os dados obtidos;
  agent: methodology_evaluator

results_analysis:
  description: >
    Analise as chunks {chunk_indexes} do batch {batch_number} do documento {target_document}. 
    Avalie os resultados apresentados, considerando:
    - A progressão lógica do texto;
    - A consistência dos dados obtidos em relação aos objetivos e metodologia empregada;
    - A coerência das conclusões com base nas evidências apresentadas;
    - A presença de possíveis inconsistências, referências ausentes ou lacunas interpretativas.
    Essas são as chunks a serem analisadas:
    {content}
  expected_output: >
    Um resumo executivo estruturado (mínimo um parágrafo) que contemple:
      - Progressão lógica dos resultados;
      - Uma avaliação da consistência dos dados apresentados em relação aos objetivos e à metodologia empregada.
      - Uma análise crítica da coerência das conclusões baseadas nas evidências (tabelas, métricas, resultados numéricos).
      - Sugestões de melhorias ou pontos a serem aprofundados, quando pertinente.
  context: [methodology_results_consistency]
  agent: critical_analyst
