topic_research:
  description: >
    Do research about "{discussion_topic}" which is a discussion topic for the subsection "{section_title}" of the "Results and Discussion" section 
    of a scientific paper. This topic has the role of {topic_description}. 
    To do so, use your tool QueryArticlesTool to generate insights aligned with the discussion topic's rhetorical purpose: {rhetorical_purpose};
    thus providing rich, evidence-based context for writing.

    **Execution Steps**:  
      1. **Construct Search Query**:  
         - Use "{discussion_topic}" and "{topic_description}" to generate a search query aligned with the discussion topic's rhetorical purpose.  
      2. **Configure `QueryArticlesTool`**:  
         - Set `doc_type` to ['draft', 'reference', 'report'].  
         - Set `top_k` to 5 initially.  
      3. **Execute Search**:  
         - Run `QueryArticlesTool` with the `search_query`.  
         - If results are insufficient (<3 relevant articles), increase `top_k` by 5, up to 20, and retry.  
      4. **Synthesize Insights**:  
         - Write a 150-300 word text in Brazilian Portuguese, ensuring:  
           - Alignment with the topic's rhetorical purpose: {rhetorical_purpose}.  
           - Consistency with section title, "{section_title}", tone: objective for Results (focus on evidence, methodology), analytical for 
             Discussion (include literature comparisons, implications).  
           - Highlight evidence, methodological comparisons, or applications relevant to the discussion topic.  

     **Guidelines for**:  
      - **Insights**: Focus on broader context that aids in understading the topic and it's role;  
      - **Subsection Tone**: For Results, emphasize objective evidence and methodology; for Discussion, include literature comparisons and implications.  
      - **Evidence-Based**: Use only `QueryArticlesTool` results, highlighting relevant data or studies.  

      **Restrictions**:  
      - Search only in `doc_type`: ['draft', 'reference', 'report'].  
      - Do not invent or modify information.  
      - `top_k` must be ≥5 and ≤20.  
      - Avoid discussing visuals or numerical results directly; focus on topic context.  

      **Success Criteria**:  
      - `QueryArticlesTool` returns results aligned with `{discussion_topic}` and `{rhetorical_purpose}`.  
      - Output is a 150-300 word text in Brazilian Portuguese, providing key insights for writting about the topic.  
  expected_output: >
    A Structured, evidence-based text, of 150-300 words in length, in Brazilian Portuguese, aligned with rhetorical purpose, providing key Insights
    for writting about "{discussion_topic}", formatted in markdown, without ```.

  agent: topic_researcher

visual_elements_research:
  description: >
    List of visual elements:

    {visual_elements_to_contextualize}

    Research each visual element of the above list, to contextualize and describe their contribution to the discussion topic "{discussion_topic}" in the 
    subsection "{section_title}" of the "Results and Discussion" section of a scientific paper, that has the role of "{topic_description}". 
    Use the tool `QueryArticlesTool` to generate evidence-based insights (100-250 words per visual, in Brazilian Portuguese) that explain how each visual 
    supports or illustrates the topic, and achives its role in the topic (e.g., summarizing data, illustrating trends).

    **Execution Steps:**

    1. Assemble a plan of action:
    - For each item in the list of visual elements:
      - Parse item's string in other to extract the visual element's `name` and `role_in_topic`;
      - Construct a search query for the item with the `name` field and {discussion_topic}
      - Clearly state that the 'doc_type' while querying the item shall be ['report', 'draft']
    - Indicate that every item shall be researched separately;

    2. Execute the plan of action sequentially:
      - For each item, execute `QueryArticlesTool` with:
        - 'search_query' parameter as the constructed search query
        - 'doc_type' as ['report', 'draft'];
        - 'top_k' as 5 initially;
      - If results are insufficient, clearly state that no viable results were found and no insights can be provided for the item
      - Else, synthesize a 100-250 word text with insights explaining the visual's contribution to the topic 
        "{discussion_topic}", using `role_in_topic` to frame its significance (e.g., how it supports findings in Results or comparisons in Discussion).

    3. Return your results for all visual elements, formated in JSON, with an object per visual element, with the keys: `name` repeating the element's 
    name, in order ot identify it, and a new `insights` key with the insights gathered in your research.

    **Restrictions:**
      - search only in `doc_type`: ['report', 'draft'].
      - Insights must be descriptive, evidence-based, and derived from `QueryArticlesTool` results, without describing the visual's appearance or inventing 
        data.

    **Success criteria:**
      - `QueryArticlesTool` executed for each visual, returning relevant results.
      - Each insight is 100-250 words in length, explaining the visual's contribution to the topic "{discussion_topic}", aligned with its `role_in_topic`.

  expected_output: >
    A JSON object with the following structure, presenting the insights for each visual element on a list in the key "about_the_visual_elements",
    where every element of the list itself an object, with the keys "name" and "insights", identifing the visual element and presenting the 
    insights, respectivaly:
    {
      "about_the_visual_elements": [
        {
          "name": "visual element name",
          "insights": "100-250 word insight in Brazilian Portuguese explaining the visual's contribution to '{discussion_topic}'.",
        }
      ]
    }
  agent: topic_researcher

numerical_results_research:
  description: >
    List of numerical results:

    {numerical_results_to_include}

    Research each numerical result in the above list to contextualize its significance for the discussion topic "{discussion_topic}" in the subsection 
    "{section_title}" of the "Results and Discussion" section of a scientific paper. Use the `QueryArticlesTool` to generate evidence-based insights 
    (100-250 words per result, in Brazilian Portuguese) that {rhetorical_purpose} the numerical result for the topic, aligning with its context 
    (e.g., statistical significance, experimental outcome).

    **Execution Steps**:
    1. For each numerical result in `List of numerical results`:
        - Extract `value`, `context` and, if not 'None', `associated_visual` from the formatted string 
          (e.g., "value: p < 0.05; context: Statistical significance; associated_visual: Figure 1").
        - Construct a search query with the fields `value`, `context`, and `discussion topic` 
          (e.g., "p < 0.05 Statistical significance for {discussion_topic}").
        - Execute `QueryArticlesTool` with:
          - `search_query`: Constructed query.
          - `doc_type`: ["report"].
          - `top_k`: 5 initially.
        - If results are insufficient (e.g., fewer than 2 relevant documents), increase `top_k` by 5, up to 15, and retry.
    2. Synthesize a 100-250 word insight (Brazilian Portuguese) explaining the result's significance to "{discussion_topic}", based on the gathered 
       context.
    3. Return insights for all numerical results, formated in JSON, with an object per item in the List of numerical results, with the keys: 
       `verbatim_value` repeating the item's numerical value, pulled from the List of numerical results, and `insights` with the insights gathered in 
       your research.

    **Restrictions**:
    - Search only in `doc_type`: ["report"].
    - Insights must be descriptive, evidence-based, and derived from `QueryArticlesTool` results, avoiding interpretations or invented data.

    **Success Criteria**:
    - `QueryArticlesTool` executed for each numerical result, returning relevant results.
    - Each insight is 100-250 words in Brazilian Portuguese, explaining the result's significance for the topic "{discussion_topic}".

  expected_output: >
    A JSON object with the following structure, presenting the insights for each numerical result on a list in the key "about_the_numerical_results",
    where every element of the list itself an object, with the keys "verbatim_value" and "insights", identifing the numerical result, and presenting 
    the insights, respectivaly:
    {
      "about_the_numerical_results": [
        {
          "verbatim_value": "value",
          "insights": "100-250 word insight in Brazilian Portuguese explaining the numerical result's significance for '{discussion_topic}'.",
        }
      ]
    }

  agent: topic_researcher

write_topic_text:
  description: >
    Write a detailed, argumentative, multi-paragraph text, in formal, precise, and academic Brazilian Portuguese, about the topic "{discussion_topic}" for 
    the subsection "{section_title}" of the "Results and Discussion" section of a scientific paper, with the rhetorical purpose of {rhetorical_purpose}. 
    Base the text on insights from `topic_research`. You must also seamlessly integrate the visual elements and numerical results listed bellow, in order 
    to fulfill the rethorical purpose.

    List of Numerical elements to include:

    {numerical_results_to_include}

    List of Visual elements to include:

    {visual_elements_to_contextualize}

    In order to aid the integration of this elements, futher context on the numerical results and the visual elements are provided from the 
    `visual_elements_research` and `numerical_results_research` tasks. Structure the text by {narrative_guidance}, set the overall tone based on 
    subsection title ({section_title}) (descriptive for Results, interpretive for Discussion), and shape the argument according to `rhetorical_purpose` 
    (e.g., presenting a finding, comparing to literature).

    The text must be scientifically robust, coherent, and well-argued, enabling readers to understand, contextualize, and critically assess the research 
    findings.

    **Context on the insights**:
    - **Research Inputs**:
      - `topic_research`: Insights on the topic's context, significance, and argumentative foundation (e.g., background, relevance). Provides the primary 
        basis for the text's argument.
      - `visual_elements_research`: A JSON object with insights detailing the contributions of visual elements (e.g., figures, tables) to the topic, if 
        assigned in the outline. All insights are part of the list in the key `about_the_visual_elements`. May be an empty list if no `visual_elements` 
        were specified for the topic (e.g., for a Discussion topic like "Limitations"). Each element of the list is an object with two keys, these being 
        `name`, identifying the visual element by name, and `insights` with the gathered insights about it. Each element of the list corresponds to an 
        item from List of Visual elements to include.
      - `numerical_results_research`: A JSON object with insights for each numerical result in List of numerical results to include, these being presented 
        in the list from the `about_the_numerical_results` key. Each element of said list is an object with two keys, these being `verbatim_value`, 
        with the numerical result's verbatim numerical value, as a way to cross reference it in the List of numerical results to include, and `insights`, 
        with the gathered insights about the result, explaining it's significance to the topic. May be an empty list if no `numerical_results` were 
        specified for the topic (e.g., for a Discussion topic like "Future Directions").

    **Execution steps:**
    1. Review `topic_research` to understand the topic's context, significance, and argumentative foundation.
    2. Review `visual_elements_research`, if provided, to extract contextual contributions of visuals.
    3. Review `numerical_results_research`, if provided, to extract the numerical results' significance.
    4. Use all the provided context to compose a 500+ word text in Brazilian Portuguese about {discussion_topic}, following these steps:
        - Structure paragraphs according to the narrative guidance: {narrative_guidance}.
        - Base the main argument on `topic_research`.
        - Make sure to include all items from the List of Visual elements and all items from the List of Numerical elements, fluidly, aiding the main 
          argument. Use the insights from `visual_elements_research` and `numerical_results_research` to contextualize contributions and significance.
        - Align tone with: descriptive and objective for Results (present findings), interpretive and analytical for Discussion 
          (compare, imply).
    5. Ensure the text is continuous, coherent, consistent and maintains a formal, academic tone.
    6. Format your response in a JSON with the keys "topic" with the discussion topic "{discussion_topic}" as it's value, and "text" with the generated 
       text as it's value.

    **Writing Directives**:
      - Write in formal, academic Brazilian Portuguese.
      - Structure the text according to the narrative guidance, following its sequence, emphasis, and references (e.g., visuals, numerical results).
      - Use the rhetorical purpose to guide the argumentative intent (e.g., "Inform" for presenting findings, "Compare findings" for literature connections).
      - Integrate `topic_research` insights as the primary argument.
      - Use the insights from `visual_elements_research` and `numerical_results_research` for contextual support. 
      - Preserve all numerical results' verbatim values exactly as provided in List of Numerical results to include.
      - Refer to visual elements contextually (e.g., "As supported by the visual analysis").
      - Maintain a descriptive tone for Results (objective, evidence-based) or interpretive tone for Discussion (analytical, literature-connected), per 
        Subsection title ({section_title}) and rhetorical purpose.
      - Ensure continuous paragraphs, avoiding lists, bullet points, or enumerated structures.

    **Constraints:**
      - Do not perform new research or invent information; use only provided insights.
      - The generated text must have 500+ words.
      - The topic must be identified exactly as "{discussion_topic}" in the output.
      - Write exclusively in Brazilian Portuguese.
      - Do not introduce critiques, judgments or opinions.

    **Success criteria:**
      - The text must be fully based on the provided insights.
      - The text is about "{discussion_topic}".
      - The final response JSON has "{discussion_topic}" for the key "topic" and the discussion topic's text for the key "text".
      - The language is Brazilian Portuguese.
      - The writing is argumentative, coherent, and flowing without lists.

  expected_output: >
    Full multi-paragraph scientific text about the topic, with 500+ words, written in brazilian portuguese, organized in a JSON 
    object with the following structure:
    {
      "topic": "{discussion_topic}",
      "text": 'Fully multi-paragraphed scientific text, with 500+ words, in Brazilian Portuguese'.
    }
  agent: technical_writer
  context: [topic_research, visual_elements_research, numerical_results_research]
